canonical/pebble

.gitignore, Makefile
This PR includes the following changes:
- A Makefile for building the project locally, based on https://github.com/juju/juju/blob/develop/Makefile
- go.mod with the project dependencies, set to 1.14 to match Juju
=> Makefile for building pebble

cmd/pebble/cmd_run.go, cmd/pebble/main.go, internal/daemon/api_test.go, internal/daemon/daemon.go, internal/daemon/daemon_test.go
$PEBBLE now defaults to /var/lib/pebble/default.
=> Support $PEBBLE_SOCKET and add $PEBBLE default.

README.md, internal/daemon/api_services_test.go, internal/logger/logger.go, internal/logger/logger_test.go, internal/overlord/servstate/manager_test.go, internal/setup/setup.go, internal/setup/setup_test.go, internal/systemd/sdnotify.go, internal/systemd/sdnotify_test.go
This also splits layer keys into independent order and label
fields. The new file format looks like 001-some-label.yaml,
where both order and label are unique. This drops the benefit of
timestamps, originally described as it being easy to blindly
create, in favor of it being better to read and manipulate.
Seems like a good tradeoff to make.
=>  Define and enforce layer filename format

internal/daemon/ucrednet.go, internal/daemon/ucrednet_test.go
A UNIX socket connection between process namespaces _appears_ to always have a pid of 0.
I have tested with non-root users and they are passed correctly by the kernel, I only tested with containerd in microk8s, so this circumstance might be just related to that environment.
This change ignores `pid == ucrednetNoProcess` and solely relies on uid.
The remote address still has to be properly formed, this is enforced by the strict regex.
=> Ignore pid=0 in socket remote address.

.gitignore, README.md, client/services.go, client/services_test.go, cmd/pebble/cmd_help.go, cmd/pebble/cmd_run.go, cmd/pebble/cmd_services.go, cmd/pebble/cmd_services_test.go, cmd/pebble/cmd_warnings.go, internal/daemon/api.go, internal/daemon/api_services.go, internal/daemon/api_services_test.go, internal/overlord/servstate/manager.go, internal/overlord/servstate/manager_test.go
This adds a new `GET /v1/services?name=foo,bar` API to fetch service status of all configured services, as well as the Go client and `pebble services` CLI command for the same. It's modeled after the `snap services` command.
See also the [design doc](https://docs.google.com/document/d/1OxaG9WUp2IR_S6qpeh9J5LgfmgW794KO9FJmGqPO_Ng/edit#).
=> Add "pebble services" command and API

internal/plan/plan.go, internal/plan/plan_test.go
When I added "pebble plan" to fetch the plan, I didn't add a custom
MarshalYAML function on plan.StringVariable, so it marshaled like so:
```
environment:
- name: FOO
value: bar
```
This changes it to matching the unmarshaling, like so:
```
environment:
- FOO: bar
```
Corresponding Python Operator Framework issue:
https://github.com/canonical/operator/issues/486
=> Fix marshaling of StringVariable to match unmarshaling

internal/overlord/servstate/handlers.go, internal/overlord/servstate/manager_test.go
Pretty self-explanatory. Fixes #17
=> Pass service description's environment variables to child process

internal/daemon/api_services_test.go, internal/overlord/servstate/manager.go, internal/overlord/servstate/manager_test.go, internal/plan/plan.go, internal/plan/plan_test.go
I missed this in the previous PR when adding "pebble services": https://github.com/canonical/pebble/pull/14
This is a breaking change, but given the rc/early status of this, we are okay with that. (There are only a few internal charms that use Pebble right now.)
=> Change default: start/stop to startup: enabled/disabled

README.md
Some README updates to reflect `default` being renamed to `startup`.
=> README updates to reflect default being renamed to startup

README.md, internal/overlord/servstate/handlers.go, internal/overlord/servstate/manager_test.go, internal/plan/plan.go, internal/plan/plan_test.go
The original intention with the list of 1-item objects was so the
environment variables were ordered in case of dependencies, like
`PATH=$PATH:/foo/var` (not that we support interpolation right now).
However, it made for an awkward config format and awkward API,
especially in the Python Operator Framework. So we're going to a plain
dictionary for the environment, and we'll resolve any dependencies
using an explicit dependency check.
See https://github.com/canonical/pebble/issues/23
=> Update layer config's "environment" to ordinary mapping

internal/daemon/api_files.go, internal/daemon/api_files_test.go
This PR includes the following:
* Add user-id, user, group-id, group fields to the list-files response (with user/group lookup cached per API call for efficiency).
* Minor fix to the list-files response to give `result: []` in the JSON instead of `result: null` when there are no results, e.g., the directory is empty.
* Change UserID/GroupID fields from int to *int as 0 is actually a valid value ("root"), so we couldn't distinguish between unset and someone trying to set both to "root".
* Add a couple more tests.
=> Files API: add user/group to list-files, and a few minor fixes

internal/daemon/api_plan.go, internal/daemon/api_plan_test.go, internal/plan/plan.go, internal/plan/plan_test.go
This addresses part of https://github.com/canonical/operator/issues/514 -- currently `POST /v1/layers` returns a generic HTTP 500 error if the layer format is incorrect, whereas it should be 400 bad request for better error handling on the client side. So add a custom error type for this case in the plan package, and handle it and return 400 in the API handler.
=> Return custom error for plan format issue; have API return 400, not 500

cmd/pebble/cmd_help.go
Shown when run with `pebble`, `pebble help`, or `pebble help --all`. Note that `PEBBLE` only applies to `pebble run`, but `PEBBLE_SOCKET` applies to all commands. New paragraph is near the end of the help output:
```
$ ./pebble 
Pebble lets you control services and perform management actions on
the system that is running them.
Usage: pebble <command> [<options>...]
Commands can be classified as follows:
Basics: run, autostart, start, stop, services, logs
Configuration: add, plan
Changes: changes, tasks
Other: warnings, okay, help, version
Set the PEBBLE environment variable to override the configuration directory 
(which defaults to /var/lib/pebble/default). Set PEBBLE_SOCKET to override 
the Unix socket used for the API (defaults to $PEBBLE/.pebble.socket).
For more information about a …
```
=> Add "pebble help" docs for PEBBLE and PEBBLE_SOCKET environment vars

internal/daemon/daemon.go
Motivation: Juju hits Pebble's "GET /v1/system-info" endpoint every 5s
as a kind of health check (https://github.com/juju/juju/blob/develop/worker/uniter/pebblepoller.go#L105).
This creates a lot of noise when people want to look at the log output.
It's kind of a hack to filter it out in this way, but we're already
doing this with /v1/changes/{change-id}, so not too bad. We can fix
this properly later, for example with more fine-grained configuration
over Pebble request logging.
This change also tightens it up a little bit (only filters GETs, so
POST /v1/changes/{change-id} will still get logged.
=> Don't log requests to /v1/system-info to avoid noise from health checks

README.md, internal/plan/plan.go, internal/plan/plan_test.go
* Fix panic when command is not set in combined layer
* Fix panic when service object/dict is null
* Also disallow use of empty string as service name
Fixes #50
=> Avoid panics in layer parsing/combining

COPYING
Add a top-level license file (`COPYING`). Will make [pkg.go.dev](https://pkg.go.dev/github.com/canonical/pebble@v0.0.0-20210628221124-0c0df5fbaa7f/client) show the docs, and good to have in any case.
=> Add GPLv3 license (to match source header and snapd)

.github/workflows/tests.yml, internal/daemon/api_files.go, internal/daemon/api_files_test.go, internal/osutil/sys/sysnum_16_linux.go, internal/osutil/sys/sysnum_32_linux.go
In Go 1.17 they changed `part.FileName()` to pass the result through `filepath.Base()` before returning, stripping off the directory component which is important for Pebble's files API. See https://golang.org/doc/go1.17#mime/multipart and https://github.com/golang/go/commit/784ef4c53135644d70f3476a4bd90010b9acff66.
Note that `ReadForm()` used in the tests also calls `part.FileName()` so we have to roll that ourselves too.
Incidentally, we'd had some discussion about this in the original PR: https://github.com/canonical/pebble/pull/25#discussion_r611891810
> I had thought about using the filename field earlier, but originally decided against it because I know some clients strip off the path part of it (per the "SHOULD NOT" warning in RFC section 2.3 that you've quoted). However, Go does …
=> Avoid use of multipart.Part.FileName() to fix files API on Go 1.17

client/changes.go, client/changes_test.go, internal/daemon/api.go, internal/daemon/api_changes.go, internal/daemon/api_changes_test.go, internal/daemon/response.go
This adds an endpoint to the Pebble API to wait for a change to be ready, with an optional timeout. It's intended for use with the upcoming "exec" feature ([spec](https://docs.google.com/document/d/1npbNQMokDUoGX1UT61CvnMq6lIJ6MnU6CwExkymHEcA/edit#) and [WIP PR](https://github.com/canonical/pebble/pull/61)). The LXD code has a similar feature, except changes are called "operations" in LXD, and there's a "wait operation" API endpoint.
This is particularly important for "pebble exec", so we can wait for the command to be finished without polling every short interval, and we can return a response immediately when the command finishes executing.
In future we could also use this new endpoint in the `pebble start` and `pebble stop` commands (and Python Operator Framework equivalents) to avoid …
=> Add wait-change API endpoint and client function

cmd/pebble/cmd_logs.go, internal/overlord/servstate/handlers.go
Fix a couple of minor issues that `go vet` raises, just to make Pebble "go vet clean" so that we can see real vet issues easily. We could also add `go vet ./...` to the GitHub Actions to ensure this stays up to date, but I decided not to for now.
Before:
```
$ go vet ./...
internal/overlord/servstate/handlers.go:167:2: unreachable code
internal/overlord/servstate/handlers.go:217:2: unreachable code
cmd/pebble/cmd_logs.go:111:2: misuse of unbuffered os.Signal channel as argument to signal.Notify
$
```
After:
```
$ go vet ./...
$
```
=> Make Pebble "go vet" clean

client/client.go, client/warnings.go, cmd/pebble/cmd_changes_test.go, cmd/pebble/cmd_version_test.go, cmd/pebble/export_test.go, internal/daemon/daemon.go, internal/daemon/daemon_test.go, internal/daemon/response.go, internal/daemon/ucrednet_test.go, internal/logger/logger_test.go, internal/osutil/mkdirallchown.go, internal/overlord/overlord.go, internal/overlord/standby/standby.go, internal/overlord/state/state.go, internal/overlord/state/state_test.go, internal/overlord/state/task.go, internal/overlord/state/task_test.go, internal/strutil/strutil.go, internal/testutil/base.go
Because of the history of pebble code being copied from snapd, there are still a bunch of snap/snapd references scattered throughout the code. This removes the most obvious ones in comments and the like. It also deletes a bunch of commented-out code in `cmd/pebble/export_test.go` (that's what version control is for :-).
I would also like to remove the systemd/standby stuff that I believe is specific to snapd, but that's a heavier change so I'd like to discuss that first.
=> Remove a bunch of snapd references

client/services.go, client/services_test.go, cmd/pebble/cmd_replan.go, internal/daemon/api.go, internal/daemon/api_logs.go, internal/daemon/api_plan.go, internal/daemon/api_services.go, internal/daemon/api_services_test.go, internal/overlord/servstate/handlers.go, internal/overlord/servstate/manager.go, internal/overlord/servstate/manager_test.go, internal/plan/plan.go
This change adds the **replan** command for restarting services that have changed or removed (we don't have remove AFAIK yet) since when they were started.
Replan acts much the same as **autostart** with the added restarting of changes.
Based on #58
Compare changes:
https://github.com/canonical/pebble/compare/hpidcock:restart...hpidcock:replan
=> Add Replan operation to restart changed services.

client/changes.go, client/exec.go, client/exec_test.go, cmd/pebble/cmd_exec.go, cmd/pebble/cmd_help.go, cmd/pebble/cmd_run.go, cmd/pebble/main.go, internal/daemon/api.go, internal/daemon/api_changes.go, internal/daemon/api_changes_test.go, internal/daemon/api_exec.go, internal/daemon/api_exec_test.go, internal/daemon/api_tasks.go, internal/daemon/daemon.go, internal/daemon/ucrednet.go, internal/overlord/cmdstate/cmdmgr.go, internal/overlord/cmdstate/handlers.go, internal/overlord/cmdstate/manager.go, internal/overlord/cmdstate/request.go, internal/overlord/overlord.go, internal/overlord/state/task.go, internal/overlord/state/task_test.go, internal/overlord/state/taskrunner.go, internal/wsutil/wsutil.go
This implements the Pebble/Go side of the [one-shot commands spec](https://docs.google.com/document/d/1npbNQMokDUoGX1UT61CvnMq6lIJ6MnU6CwExkymHEcA/edit) for command execution using websocket communication, including the Go client and `pebble exec` CLI.
**Other notes for the code reviewer:**
* I've added a number of tests for the API with use-terminal=false. They're not exactly "unit" tests as they run real commands and use the Go client for connecting to the websockets, but this makes the code and tests significantly simpler, and they run fast.
* There is currently only one trivial test with use-terminal=true, as it's hard to test terminal-specific features in Go tests. Instead, I suggest we focus on manual testing for testing terminal interactivity (see "Terminal resizing" under manual …
=> One-shot commands (pebble exec)

client/logs.go, client/logs_test.go, cmd/pebble/cmd_logs.go, cmd/pebble/cmd_logs_test.go, internal/daemon/api_logs.go, internal/daemon/api_logs_test.go
For rationale for this change, see discussion at https://github.com/canonical/pebble/issues/83#issuecomment-973980643.
This removes the pointer on the `N *int` (number of logs) parameter to be just a plain `int`. When calling `Logs` (non-follow), the default is the server-specified default (currently 30). When calling `FollowLogs`, the default is 0 (don't show any buffered logs).
This PR also changes the server API to have the same semantics (except that the default is "unset n" rather than "zero N"). This shouldn't affect any real users -- the `pebble logs` CLI command already sends through an explicit "n" value anyway. Any negative "n" values other than -1 are now an error (but this won't affect any clients).
I've also changed the default number of logs from 10 to 30 (see discussion on …
=> Simplify client.Logs "N" parameter and avoid pointer

internal/daemon/api.go, internal/daemon/api_test.go, internal/daemon/daemon.go, internal/daemon/daemon_test.go, internal/overlord/overlord.go, internal/overlord/overlord_test.go, internal/overlord/restart/restart.go, internal/overlord/restart/restart_test.go, internal/overlord/servstate/handlers.go, internal/overlord/servstate/manager.go, internal/overlord/servstate/manager_test.go, internal/overlord/servstate/servstatetest/restart.go, internal/overlord/standby/export_test.go, internal/overlord/standby/standby.go, internal/overlord/standby/standby_test.go, internal/overlord/state/state.go, internal/overlord/state/state_test.go, internal/overlord/state/taskrunner_test.go
This PR crossports the restart package and related changes from snapd.
It brings pebble inline with the snapd upstream to simplify state by removing the restart concerns into its own package with good separation.
Relevant commits pulled across https://github.com/snapcore/snapd/commits/master/overlord/restart
=> Crossport restart package from snapd.

client/signals.go, client/signals_test.go, cmd/pebble/cmd_autostart.go, cmd/pebble/cmd_help.go, cmd/pebble/cmd_replan.go, cmd/pebble/cmd_signal.go, cmd/pebble/cmd_signal_test.go, internal/daemon/api.go, internal/daemon/api_services_test.go, internal/daemon/api_signals.go, internal/daemon/api_signals_test.go, internal/overlord/servstate/handlers.go, internal/overlord/servstate/manager.go, internal/overlord/servstate/manager_test.go
This implements spec [JU029 Pebble: sending signals to services](https://docs.google.com/document/d/1R9gdQU7q1CdH3raqLeB9d86pICbOSpm0P04P_CNF2g0/edit#). Specifically:
* An API to send a signal to one or more running services:
- `POST /v1/signals {"signal": "SIGHUP", "services": ["s1", "s2"]}`
* A Go client to send a signal:
- `c.SendSignal(&client.SendSignalOptions{Signal: "SIGHUP", Services: []string{"s1, "s2"})`
* A CLI command to send a signal:
- `pebble signal HUP s1 s2 ...`
One question I had was whether the API should return an error if the service being signaled is not running. After discussion with Harry we decided to mimic the behavior of the Unix `kill` command, which gives an error if the pid is not active. But that's open for debate -- it will mean if you call `send_signal()` …
=> Add signals API to send a signal to one or more services

internal/overlord/servstate/export_test.go, internal/overlord/servstate/handlers.go, internal/overlord/servstate/manager.go, internal/overlord/servstate/manager_test.go
This fixes a bug in Replan not updating the stored `service.config` value due to bad logic I introduced in https://github.com/canonical/pebble/pull/79/files#diff-c2607d6e10ee84455ecce459b40a302a3a9f44197dc7a2205c52c0cc76c8bfaaR370. I've also added a test for this case.
It also fixes a similar bug where a manual stop/start (or restart) sequence didn't update the stored service config -- I introduced this bug in the same commit.
=> Fix bug with replan/start/restart not updating internal config

internal/overlord/servstate/handlers.go
Was included as a drive-by update in https://github.com/canonical/pebble/pull/101, but making it a separate PR to avoid noise in that one.
=> Add a comment to serviceState about the state diagram

internal/daemon/daemon.go
Now that `/v1/health` is done via the standard daemon API endpoints (albeit using an HTTP server) we're logging hits to it every 5s when deployed on Juju K8s (the probes hit it every 5s). Add `/v1/health` to the list of "skip log" URLs to avoid spamming the logs.
=> Don't log requests to /v1/health (similar to /v1/system-info)

internal/daemon/api.go, internal/daemon/api_services.go, internal/daemon/api_services_test.go
When a replan was executed and there were no services to stop/start
(for example, when there are no startup: enabled services), the
POST /v1/services endpoint would panic due to the unhandled case.
Handle this case, which is a change with no tasks -- it needs to be a
real change because the endpoint returns a change ID (the client is
expecting a change ID or an error). It shouldn't be an error because
the replan is actually successful, there's just nothing to do.
Also add a test for this case.
This also removes newChange, which was only used in one place, and
less clear than just including it inline.
Fixes #94
=> Fix panic when replan is called and there are no services to stop/start

internal/daemon/daemon.go
This is primarily so that when you're debugging locally and press
Ctrl-C to terminate the Pebble server, an open "pebble logs -f" stream
doesn't block shutdown for 25 seconds. There's no need for this timeout
to be so long, so reduce it.
Note that this is only the time it takes to shut down the API server
(perhaps it should be called something more specific like
`serverShutdownTimeout`).
After the shutdown timeout is elapsed, the server terminates the
connection and the client gets an "EOF" error.
Fixes #55
=> Reduce server shutdown timeout from 25s to 1s

cmd/pebble/cmd_logs.go
It would be quite a significant refactoring to have "pebble logs -f"
subscribe to new services being started and wire that through, so for
now at least, just document the current behaviour. It seems unlikely to
affect people in practice, as the service(s) you're debugging will
likely be running.
See https://github.com/canonical/pebble/issues/56
=> Document that "pebble logs -f" only follows currently-running services

internal/daemon/daemon_test.go, internal/overlord/checkstate/checkers.go, internal/overlord/checkstate/checkers_test.go, internal/overlord/checkstate/manager_test.go, internal/overlord/cmdstate/handlers.go, internal/overlord/servstate/handlers.go, internal/overlord/servstate/manager.go, internal/overlord/servstate/manager_test.go, internal/overlord/servstate/reaper.go, internal/reaper/reaper.go, internal/systemd/systemd_test.go, internal/testutil/exec.go, internal/testutil/exec_test.go
This PR sets Pebble as a Linux "child subreaper", meaning if it's not running as PID 1, it'll get zombie (non-waited-on) children re-parented to Pebble rather than whatever *is* running as PID 1, so that we can reap them.
It also adds a "reaper" background task whose main purpose is to ensure that zombie / non-waited-on child processes are reaped (i.e., waited on and removed from the process table).
The reaper works by waiting for `SIGCHLD`, and on receipt of that signal, reaps as many waiting children as are available. For PIDs that Pebble has started directly using `os/exec`, instead of calling `cmd.Wait` we now call `reaper.WaitCommand()` -- this registers the PID with the reaper so it can notify the caller when it exited.
This is a bit klunky, but it avoids a race condition between …
=> Make Pebble a child subreaper and reap zombie children

internal/daemon/api_files.go, internal/daemon/api_files_test.go, internal/osutil/io.go, internal/osutil/io_test.go
And use this explicit chmod flag for file writes coming from the files api.
Fixes #80
=> Add option for explicit chmod with atomic file write.

README.md
The Pebble configuration do not have to define any services. The only side effect
is that no default services will be started when the daemon starts (and a notice
message will be printed out).
```
flotter@flotter-pc:~/pebble$ ./pebble run
2022-06-20T13:25:18.021Z [pebble] Started daemon.
2022-06-20T13:25:18.028Z [pebble] POST /v1/services 3.095222ms 400
2022-06-20T13:25:18.029Z [pebble] Cannot start default services: no default services
```
This PR corrects the wording in the README.md file to reflect services are optional.
=> Correct services in the YAML schema docs as optional

README.md, cmd/pebble/cmd_run.go, internal/daemon/daemon.go, internal/daemon/daemon_test.go, internal/overlord/servstate/manager.go, internal/overlord/servstate/manager_test.go, internal/overlord/servstate/request.go
This PR makes Pebble try to gracefully stop all services when SIGINT (Ctrl+C) or SIGTERM/SIGQUIT is received. This goes via the regular "stop" task process, which sends SIGTERM to each process, then waits up to the killWait time (5s) before sending SIGKILL.
The "stop" tasks are added to a new "stop" change. I considered whether a change is appropriate here (given the recent discussion about events), and I do think it is. For one, this is a user-initiated action (Ctrl-C pressed / signal sent), and besides, the tasks are ordinary "stop" tasks to stop the services involved, so they need to be part of an associated change to kick them off. Later when we add events, we can additionally fire a shutdown event of some kind.
Output of `pebble changes` and `pebble tasks` showing the record of the …
=> Stop all services when Ctrl+C or SIGTERM/SIGQUIT received

.github/workflows/tests.yml, internal/overlord/cmdstate/handlers.go, internal/overlord/servstate/handlers.go, internal/overlord/servstate/manager_test.go
This ensures that Pebble overrides the `HOME` and `USER` environment variables when starting a service if the service config's `user` and `group` are set. It addresses the issue described in #126.
Also add TestUserGroup to test this (must be run as root).
Fixes #126.
=> Explicitly set HOME and USER env vars if service user+group set

internal/overlord/checkstate/checkers.go, internal/overlord/checkstate/checkers_test.go, internal/overlord/checkstate/manager_test.go
Currently it inherits them if you don't have any environment variables
set in the config, but does not inherit them if you have one or more
set. This is a quirk of the implementation, and how the
exec.Command.Env field works. Make them not inherited in both cases to
be consistent.
Trivial fix, but also add tests for both cases.
Fixes #127
=> Make exec checks consistently not inherit parent environment variables

cmd/pebble/cmd_add_test.go, cmd/pebble/cmd_checks_test.go, cmd/pebble/cmd_logs_test.go, cmd/pebble/cmd_plan_test.go, cmd/pebble/cmd_services_test.go, cmd/pebble/cmd_signal_test.go, cmd/pebble/cmd_version_test.go, cmd/pebble/cmd_warnings_test.go
This is a relatively small patch that improves upon the existing test suites for well-tested Pebble commands to achieve near-complete code coverage. I'm working on adding tests for the rest of commands but as these will be slightly larger patches I will do separate PRs for each of them.
=> Bump test coverage for some commands

cmd/pebble/cmd_autostart_test.go
This patch adds coverage for the `pebble autostart` command.
=> Add tests for autostart command

cmd/pebble/cmd_replan_test.go
This patch adds coverage for the `pebble replan` command.
=> Add tests for the replan command

cmd/pebble/cmd_warnings.go, internal/osutil/io.go, internal/osutil/mountentry_linux.go, internal/overlord/state/change.go, internal/overlord/state/change_test.go, internal/overlord/state/state.go, internal/overlord/state/taskrunner_test.go, internal/progress/progress.go, internal/servicelog/formatter.go, internal/strutil/pathiter.go, internal/strutil/shlex/shlex.go, internal/strutil/version.go, internal/testutil/exec.go, internal/testutil/intcheckers.go, internal/timeutil/schedule.go
Run `go fmt ./...` with Go 1.19 (and fix up a couple of places manually).
=> Update to Go 1.19 "go fmt" comment formatting

internal/osutil/osutil_darwin.go
When copying code from snapd to pebble we missed ErrDarwin so that pebble can be compiled on Darwin.
See https://github.com/snapcore/snapd/blob/61b66aaa1beb861f308ea7dd75c2f0c042bf29a3/osutil/osutil_darwin.go for reference.
=> Adds missing ErrDarwin error.

README.md
This PR adds a large section of documentation to the README about how to use Pebble, and how some of its major features work. This is intended as a mini user manual; several people have asked about how these things work, and I've previously had to say "sorry, it's documented in the code". :-)
=> Add "Using Pebble" documentation to README

HACKING.md, README.md, client/changes.go, client/checks.go, client/client.go, client/doc.go, client/example_test.go, client/exec.go, client/files.go, client/logs.go, client/plan.go, client/services.go, client/signals.go, client/warnings.go, cmd/pebble/cmd_help.go
This add a brief package doc comment to the client package, as well as short doc comment to (I think!) every type and method in the client package. This is part of a larger effort to document Pebble more thoroughly -- this PR focusses on the Go reference docs for the `client` package.
Also make a few updates to the README. Removed two bullet points from "Some details worth highlighting", as those are discussed in detail below. Link to API docs instead of providing an inline example. Update "TODO" section items.
Also add an example for the client package docs. It's not really run (in the "too hard basket" for now; I've tested it locally though), but at least it's type checked.
=> Flesh out client package docs; small README improvements

README.md
Amends #168 - I made some changes but forgot to remove the "Installation" entry I had added to the table of contents.
=> Remove unused "Installation" heading in contents

client/services.go, client/services_test.go, cmd/pebble/cmd_services.go, cmd/pebble/cmd_services_test.go, internal/daemon/api_services.go, internal/overlord/servstate/handlers.go, internal/overlord/servstate/manager.go, internal/overlord/servstate/manager_test.go
This PR adds a `current-since` field to the API, meaning the time at which the "current" field last changed, for example started (current changed from `inactive` to `active`), and so on. It's related to https://github.com/canonical/pebble/issues/104 (though in a previous iteration it was "start time", not "curren since").
Here's how it looks like the CLI:
```
$ pebble services
Service  Startup  Current  Since
test2    enabled  active   today at 17:08 NZST
$ pebble services --abs-time
Service  Startup  Current  Since
test2    enabled  active   2022-04-28T17:08:45+12:00
```
This PR also removes the "restarts" field which isn't being used and was internal-only. Per #104, we're going to use changes/tasks or events instead.
=> Add "current-since" field to services API and CLI

.github/workflows/tests.yml
- Disable fail-fast for unit tests, so that failing on one version of Go doesn't cancel the tests for all other versions.
- Upgrade actions/setup-go to v3 - as a result, we can now get the Go version from `go.mod`.
- Run unit tests on Go 1.18 and 1.19 as well.
=> CI improvements

.github/workflows/tests.yml
When a go test fails due to a panic() inside a spawned child goroutine, only the
stack trace of the goroutine is provided in the CI logs. This makes it impossible
to infer which test in a suite actually caused the failure.
Make CI tests run with -check.vv to print test entry and progress messages to
add context in the event of a child goroutine panic().
For example, S.TestUserGroup would be shown as:
START: manager_test.go:488: S.TestUserGroup
START: manager_test.go:138: S.SetUpTest
PASS: manager_test.go:138: S.SetUpTest	0.001s
START: manager_test.go:174: S.TearDownTest
PASS: manager_test.go:174: S.TearDownTest	0.000s
In the event of any failures, it would be printed after the start message, allowing us
to pinpoint the test that caused the failure.
Verbose printing is only shown for …
=> Make CI unit test failures more verbose

.github/workflows/tests.yml
Should remove the following deprecation warning in CI:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
=> [CI] Update actions/checkout to v3

internal/overlord/servstate/handlers.go, internal/overlord/servstate/manager_test.go
When a service under Pebble's control exits with code 0 and has it's OnSuccess service key configured to ignore Pebble set's the services state to one of error.
This change configures this logic so that when a service layer specifies ignoring a service that has exited with a code of 0 it is now placed into an inactive state.
For this PR I have not enabled any new tests instead modified the ones we have that were already checking this condition.
=> Changes service status on success ignore.

README.md, internal/daemon/daemon.go, internal/overlord/servstate/export_test.go, internal/overlord/servstate/handlers.go, internal/overlord/servstate/manager.go, internal/overlord/servstate/manager_test.go, internal/plan/plan.go, internal/plan/plan_test.go
- This change adds a new key to the Pebble service plan spec called kill-delay. This allows the author of a service definition to control the amount of time Pebble allows before sending SIGTERM and SIGKILL to a process.
- This change also increases the default duration afforded to pebble for kill-delay from 5s to 25s.
=> [JUJU-1887] Adds kill delay duration for service shutdown.

cmd/mkversion.sh
By default it was populating the 'version_generated.go' file into the top level directory, but we want to populate it in the same directory as the cmd package. (That is where 'pebble version' currently looks for it.)
I did test just running `go generate ./...` from the top level directory, and running in as `cd cmd; go generate`, and it picked up the version string. They are still just git hashes, because we haven't done a version tag, but I can see that mkversion.sh is using 'git describe' as you would expect.
=> Change the generate directory to 'cmd/'

README.md
small correction in Layer specification section in README.md. updated timeout definition: `timeout must not be more than the period` is the correct description NOT `timeout must not be less than the period`. defaults of timeout and period confirm that.
=> Fix checks timeout definition in README.md

.github/workflows/binaries.yml
This simplifies, and avoids the 5-second delay from trying to look up the server version. Note that the `--client` arg for `pebble version` was added very recently in https://github.com/canonical/pebble/pull/208.
=> Use "pebble version --client" in GitHub Action now that that exists

internals/daemon/api_exec.go, internals/daemon/api_exec_test.go, internals/daemon/api_test.go, internals/osutil/env.go, internals/osutil/env_test.go, internals/osutil/export_test.go, internals/overlord/checkstate/checkers.go, internals/overlord/checkstate/checkers_test.go, internals/overlord/cmdstate/request.go
Currently, the environment variables from the pebble daemon are not inherited while executing ``pebble exec`` commands.
Change this behavior and inherit all environment variables available to the pebble daemon, in pebble exec.
Additionally, per discussion, this changes the health checks of "exec" type to inherit the daemon's environment as well.
=> fix: pebble exec and "exec" health checks inherit environment from daemon

README.md, internals/daemon/api_exec_test.go, internals/osutil/user.go, internals/osutil/user_test.go, internals/overlord/checkstate/checkers.go, internals/overlord/checkstate/checkers_test.go, internals/overlord/cmdstate/handlers.go, internals/overlord/servstate/handlers.go, internals/overlord/servstate/manager_test.go
When user and group (or user ID and group ID) options are given when running services and they're equal to the current user and group, avoid setting os/exec's `syscall.Credential` `Uid` and `Gid`, because they require root. In the case when they're explicitly asking to run the command as the current user, we can just run it directly, without requiring root.
This goes for services, exec (one-shot commands), and health checks of type "exec".
This PR also fixes a long-standing bug in the user/group options for "exec" health checks not working at all. This was due to not setting `cmd.SysProcAttr`, so the `cmd.SysProcAttr.Credential = ...` line would panic with a nil pointer error.
Also a drive-by fix to the README to update to the new terminology. See also …
=> Allow non-root user to specify current user/group when running commands

README.md, internals/overlord/servstate/handlers.go, internals/overlord/servstate/manager_test.go, internals/plan/plan.go, internals/plan/plan_test.go
Fixes #158 (in preparation for #159)
=> Add support for service's to configure working directory

internals/overlord/checkstate/manager.go, internals/overlord/checkstate/manager_test.go
**checkstate: make check runners exit cleanly**
The checks manager uses contexts to cancel check runners. This happens
during checkstate.PlanChanged() when the previous checkers are all
terminated, and the new checker definition is applied.
However, context cancellation is asynchronous (as highlighted in the
context documentation), so the check runners will continue to complete
even after the context cancellations returned.
Due to this race condition, the runner can still launch a check even after
the context cancellation is complete.
This problem is reproduced here:
https://gist.github.com/flotter/f6bf32d7cc33cb1d53a3ddc39fc3b64c
The result of this is easily seen the following unit test failure:
panic: internal error: reaper must be started
goroutine 75 [running]: …
=> checkstate: make tests more robust

internals/daemon/api_exec.go, internals/daemon/api_exec_test.go
This PR improves the error messages with `pebble exec` (at the API level), mainly so that if the working directory you specify doesn't exist, it's clear that the "no such file or directory" message is referring to the working dir and not the executable.
For example, the current error messages (shown below) looks like the `/usr/bin/echo` binary doesn't exist, when it's actually the `-w` working dir you've specified that doesn't exist:
```
$ pebble exec -w /noexist -- /usr/bin/echo foo
error: cannot perform the following tasks:
- exec command "/usr/bin/echo" (fork/exec /usr/bin/echo: no such file or directory)
```
This update isn't perfect, because it doesn't check the permissions of the working directory (I believe `x` is required), but definitely an improvement for the case at hand.
Fixes …
=> Improve error messages with exec, especially if working dir missing

README.md, internals/plan/plan.go, internals/plan/plan_test.go
#223 was proving too complex, so we've come up with an alternative way to specify which services each log target should collect logs from.
The log target spec now has a `services` field, which accepts a list of services to collect log targets from.
```yaml
log-targets:
tgt1:
services: [svc1, svc2]
```
This replaces the old `log-target.selection` field, which has now been removed. The `services` field is also much more expressive than `selection`, so it also removes the need for the `service.log-targets` field. **Effectively, `log-target.services` is now the only place to specify which services' logs go to which log targets.**
Some bonus features:
- Use the `all` keyword to match all services (including future services):
```yaml
tgt1:
services: [all]
```
- Use `-svc` to remove a service …
=> [JUJU-3777] Multiplex services to log targets using only a `log-target.services` field

.github/workflows/snap.yml
closes https://github.com/canonical/pebble/issues/241
**BEFORE MERGING:** This new job requires a secret for letting Snapcraft authenticate with the Snap Store. I'm still in the process of getting a Pebble-specific bot account for this, so **before merging**, please double-check the current status with me so that I can also share said secret privately. 
This PR is built on top of https://github.com/canonical/pebble/pull/179, allowing us to automatically promote the Pebble snap to `latest/candidate` every time there is a new Pebble release on GitHub.
- this workflow is now also triggered on every GH release
- during the snap tests, the Pebble client version is inferred so that it can be used for promoting the right snap version
- on release, we wait for the Store to finish the snap builds …
=> ci: promote snap to candidate on every release

internals/testutil/exec.go, internals/testutil/exec_test.go
testutil: support empty string args in fakecommand
FakeCommand allows unit tests to check which command-line arguments
were passed, by recording a log of calls with their arguments.
The following examples cannot be tested with FakeCommand:
1. shutdown -r "+0" ""
2. echo ""
3. configure --program-prefix ""
The empty string argument confuses the command parser in testutil.
The issue is that both the argument (\000) and command delimiter
(\000\000) uses null characters, which makes the command split
operation split on the first occurrence of two null chars. This
is an invalid assumption for an empty string argument, which will
be presented as two argument delimiters, without anything in
between, appearing like a command delimiter.
To add support for this:
- Change the command delimiter from …
=> testutil: support empty string args in fakecommand

internals/daemon/daemon_test.go, internals/testutil/exec_test.go
The usage of testutil.FakeCommand requires the test environment to start and stop the reaper in the case where the reaper option is enabled.
For example, in internals/daemon/daemon_test.go:
:
cmd := testutil.FakeCommand(c, "shutdown", "", true) :
However, in daemon_test.go, the code is currently relying on the service manager, provided by the overlord, to start the reaper. This is not a safe solution as not all test implementations may actually run the real overlord code, and even if they do, we have a potential race condition.
daemon.Init() -> overlord.New() -> servstate.NewManager() -> reaper.Start()
The following changes are introduced:
- Add reaper.Start() and reaper.Stop() to the daemon test setup and teardown.
- Add a reaper based test for testutil.FakeCommand().
=> daemon: FakeCommand usage requires reaper.Start()

internals/overlord/servstate/manager.go, internals/overlord/servstate/manager_test.go
**servstate: backoff svcs should be stopped on exit**
The default behaviour today for a service that exits is that Pebble will
auto-restart the service. This process has a built in back-off strategy
which means that on exit a timer is set to restart the service after
the back-off period expires.
The way to prevent a service in back-off to restart is to explicitly stop
the service (this case is covered in a unit test).
When the Pebble daemon starts a graceful exit, it has to first stop all
running services by requesting this explicitly, and waiting for the change
request to complete.
However, services currently scheduled for restart (back-off) is not currently
stopped through this request. This is an issue because the restart mechanism
relies on the reaper package, which is stopped …
=> servstate: test stability improvements

.github/workflows/binaries.yml, .github/workflows/tests.yml
As established in #171, Pebble no longer needs to support Go versions before Go 1.20. Hence, it no longer makes sense to run the unit tests with Go versions before 1.20.
=> Run unit tests only on Go 1.20

snap/snapcraft.yaml
Based on https://github.com/canonical/pebble/pull/171, this PR is simply making sure the Pebble snap is built with Go 1.20 instead of whatever the latest stable Go version is in the snap store.
=> Build Pebble snap with Go 1.20

internals/overlord/servstate/manager_test.go
This patch improves the following tests, all related to checker functionality in servstate observed when running under stress:
TestOnCheckFailureRestartWhileRunning
TestOnCheckFailureRestartDuringBackoff
TestOnCheckFailureIgnore
TestOnCheckFailureShutdown
Since we are unit testing servstate, and not checkstate, this patch adds code to more effectively control (mock) when the check failure actions are delivered during the test. This removes the requirement for tests to rely on finely tuned delays to check various service life-cycle states.
The following changes are made:
- Round some of the delays to multiples of 100ms to highlight the fact these values are less important now. Delays intended to present infinite are replaced with 10s to ensure severe failures are observed if the test does …
=> servstate: remove on-check-failure test races

.github/workflows/tests.yml, internals/daemon/api_files_test.go, internals/overlord/cmdstate/request.go
Resolves https://github.com/canonical/pebble/issues/260 and https://github.com/canonical/pebble/issues/263
As part of https://github.com/canonical/pebble/pull/234/files, pebble inherit's the daemon's environment when compiling the request to send to the pebble daemon. As a result, the `HOME` and `USER` environment variables are also inherited (especially troublesome as the `HOME` variable causes permission errors when executing `pebble exec --user=ubuntu --group=ubuntu whoami` given that the daemon user is running as `root`
The code already correctly sets the `HOME` and `USER` variables in `request.go` based on the specified user and user's home directory. Therefore, nullify these env vars when inherited from the daemon's environment.
```
root@host:/home/ubuntu/mnt/pebble# …
```
=> Do not inherit HOME and USER env vars from pebble daemon environment

.github/workflows/binaries.yml
Follow up from a [conversation](https://github.com/canonical/chisel/pull/91#discussion_r1289629560) with @rebornplusplus which  made me realise that our release archives actually create a tarball containing a directory named `.` with the files within it.
This change makes all the files appear at the top-level of the archive.
=> ci: place files at top-level of release archives

HACKING.md
In the spirit of documenting Pebble conventions, add a section about log/error message conventions to `HACKING.md`, so I don't forget.
Also, I must have forgotten to add the "Code style" section to the table of contents, so add this in.
=> Add section about log/error messages to HACKING.md

HACKING.md
I'm posting this here for discussion. I've grown to quite like the [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification. I think it naturally brings consistency to commit messages when reading the short log, and also encourages me personally to think carefully when I'm committing as to how I should break things up.
We've actually got some conventions emerging, but because we're not enforcing it, the commit log is starting to look a little untidy to my obsessive eye. 
Proposing this as a convention - happy for comments etc. If we can agree on the style, we can introduce a CI check.
Including some examples from the source of this commit:
```
feat: checks inherit context from services
test: increase unit test stability
feat(daemon): foo the bar …
```
=> docs: introduce conventional commit guidelines

internals/daemon/api_logs.go, internals/daemon/daemon.go, internals/daemon/response.go, internals/overlord/checkstate/checkers.go, internals/overlord/cmdstate/handlers.go, internals/overlord/servstate/handlers.go, internals/overlord/servstate/manager_test.go, internals/overlord/stateengine.go, internals/reaper/reaper.go
Use `os.exec`'s [`Cmd.WaitDelay`](https://pkg.go.dev/os/exec#Cmd.WaitDelay) to ensure `cmd.Wait()` returns in a reasonable timeframe if the goroutines that `cmd.Start()` uses to copy stdin/out/err are blocked when copying due to a sub-subprocess holding onto them. Read more details about the issue in https://github.com/golang/go/issues/23019 and the proposed solution (that was added in Go 1.20) in https://github.com/golang/go/issues/50436.
This solves [issue 149](https://github.com/canonical/pebble/issues/149), where Patroni wasn't restarting properly even after a `KILL` signal was sent to it. I had originally mis-diagnosed this problem as an issue with Pebble not tracking the process tree of processes that daemonise and change their process group (which is still an issue, but is not …
=> fix(servstate): use WaitDelay to avoid Command.Wait blocking on stdin/out/err

internals/testutil/exec_test.go
Currently when you run:
```
go test -count=2 -v ./internals/testutil/ -check.v
```
It fails with the following error:
```
FAIL: exec_test.go:89: fakeCommandSuite.TestFakeShellchecksWhenAvailable
using shellcheck: "/usr/bin/shellcheck"
exec_test.go:106:
c.Assert(fakeShellcheck.Calls(), check.DeepEquals, [][]string{
{"shellcheck", "-s", "bash", "-"},
})
... obtained [][]string = [][]string(nil)
... expected [][]string = [][]string{[]string{"shellcheck", "-s", "bash", "-"}} ... Difference:
...     [][]string[0] != [][]string[1]
```
Because TestFakeShellchecksWhenAvailable relies on global state. Reset this global state before each run to allow this package's tests to be run more than once (-count=N where N>1).
=> test(testutil): fix tests when run with -count=2

internals/testutil/exec_test.go
Currently TestFakeCommandWithReaper is half using the reaper: it's setting the withReaper flag to true, but not using reaper versions of the command-running functions. Do that. Also, only start/stop the reaper in the one test that needs it.
This should fix intermittent failures like [this one](https://github.com/canonical/pebble/actions/runs/5734108330/job/15539937916?pr=256):
```
START: exec_test.go:42: fakeCommandSuite.TestFakeCommand
using shellcheck: "/usr/bin/shellcheck"
exec_test.go:46:
c.Assert(err, check.IsNil)
... value *os.SyscallError = &os.SyscallError{Syscall:"waitid", Err:0xa} ("waitid: no child processes")
FAIL: exec_test.go:42: fakeCommandSuite.TestFakeCommand
```
=> test(testutil): fix usage of reaper in exec_test.go

internals/daemon/daemon_test.go
Currently the TestRebootHelper test fails intermittently with the following failure ([example log](https://github.com/canonical/pebble/actions/runs/5888109857/job/15968661905?pr=267)):
```
daemon_test.go:773:
c.Assert(err, IsNil)
... value *os.SyscallError = &os.SyscallError{Syscall:"wait", Err:0xa} ("wait: no child processes")
```
This is because we're running the reaper, but systemdModeReboot doesn't use or know about the reaper. So avoid starting/stopping the reaper in the setup and teardown; daemon.New and Daemon.Stop -- via the service manager) starts/stop it in any case. And set the FakeCommand withReaper flag to false here as the reaper isn't running there now.
Fixes #186
=> test(daemon): don't start/stop reaper is setup/teardown

.github/.golangci.yml, .github/workflows/lint.yml, internals/daemon/daemon.go, internals/daemon/daemon_test.go, internals/overlord/managers_test.go, internals/overlord/overlord.go, internals/overlord/overlord_test.go, internals/overlord/stateengine.go
This change enables an external application importing Pebble to extend the overlord functionality by adding additional managers.
Example overlord extension:
```go
package ovldext
type OverlordExtension struct {
fooManager *foostate.Manager
barManager *barstate.Manager
}
func New() *OverlordExtension {
return &OverlordExtension{}
}
func (oe *OverlordExtension) ExtraManagers(o *Overlord) ([]overlord.StateManager, error) {
oe.fooManager, err := foostate.NewManager(o.State(), o.TaskRunner())
if err != nil {
return nil, err
}
oe.barManager, err = barstate.NewManager(o.State(), o.TaskRunner())
if err != nil {
return nil, err
}
return []overlord.StateManager{oe.fooManager, oe.barManager}, nil
}
func (oe *OverlordExtension) FooManager() *foostate.Manager { return oe.fooManager }
func (oe …
```
=> feat(overlord): allow adding external managers

internals/cli/cli.go, internals/cli/cmd_add.go, internals/cli/cmd_autostart.go, internals/cli/cmd_changes.go, internals/cli/cmd_checks.go, internals/cli/cmd_enter.go, internals/cli/cmd_exec.go, internals/cli/cmd_help.go, internals/cli/cmd_logs.go, internals/cli/cmd_ls.go, internals/cli/cmd_mkdir.go, internals/cli/cmd_plan.go, internals/cli/cmd_replan.go, internals/cli/cmd_restart.go, internals/cli/cmd_rm.go, internals/cli/cmd_run.go, internals/cli/cmd_services.go, internals/cli/cmd_signal.go, internals/cli/cmd_start.go, internals/cli/cmd_stop.go, internals/cli/cmd_version.go, internals/cli/cmd_warnings.go, internals/cli/last.go, internals/cli/wait.go
This patch gets rid of the `clientMixin` in command structs in favor of passing a `CmdOptions` struct to the `New` (formerly `Builder`) function in `CmdInfo`.
Example usage:
```go
type cmdFoo struct {
/* ... */
client *MyClient
}
func init() {
AddCommand(&CmdInfo{
/* ... */
New: func(opts *CmdOptions) flags.Commander {
return &cmdFoo{client: &MyClient{opts.Client}}
},
})
}
func (cmd *cmdFoo) Execute(args []string) error {
return cmd.client.Foo()
}
```
```go
import "github.com/canonical/pebble/client"
type MyClient struct {
*client.Client
}
func (c *MyClient) Foo() error {
/* ... */
}
```
=> feat(cli): enable extended client access

README.md
It currently says that "requires" does ordering ("Before ... first"), but that's not true -- "requires" only specifies dependencies. It "before" and "after" that does ordering.
Also note that limited usefulness of before/after as Pebble doesn't really check that a service is "up", just waits 1s.
=> docs: fix "service dependencies" section in README

README.md
Thanks @troyanov for pointing out the mistake.
See also recent changes in #290 (though that didn't introduce this problem).
=> docs: fix polarity of before/after in "service dependencies" section

internals/daemon/daemon.go
The following PR provided Pebble derived projects to extend the supplied daemon HTTP API handlers.
https://github.com/canonical/pebble/pull/265
However, currently such a handler cannot access the daemon, even though we added a daemon method to also expose the Overlord.
```go
func v1PostDevice(*daemon.Command, req *http.Request, _ *daemon.UserState) daemon.Response {
:
// Cannot access c.d (daemon is private)
ovld := c.d.Overlord()
:
}
```
This PR adds c.Daemon() to allow access inside externally defined HTTP API handlers.
=> feat(daemon): daemon access for API extensions

internals/overlord/servstate/state-diagram.dot
Similar fix to https://github.com/canonical/pebble/pull/304 now that `internal` moved to `internals`.
=> chore: fix path in dot command in state-diagram.dot comment

internals/daemon/api_exec.go, internals/daemon/api_exec_test.go, internals/overlord/cmdstate/request.go
Currently if you create a user without a home directory (or a home directory that doesn't exist), `pebble exec` fails with a hard-to-understand error message which implies the executable you're trying to run doesn't exist. (As #189 points out, you can easily create a user without creating the home directory.)
For the [first version](https://github.com/canonical/pebble/pull/309/commits/ccf677e23f1ddea506abe8e043160fe7e4d72984) of this PR, we made that not fail (and use "/" as the working dir). However, as @hpidcock pointed out, that's problematic, and it probably should fail. Otherwise the caller might call `rm -rf bin` with `HOME=/home/ubuntu`, which if it doesn't exist will fall back to deleting `/bin` -- likely not what you want.
So it's better to return an error in this case. The charm …
=> fix(cmdstate): better error message if $HOME dir doesn't exist

client/health.go, client/health_test.go, internals/cli/cmd_checks.go, internals/cli/cmd_health.go, internals/cli/cmd_health_test.go, internals/cli/cmd_help.go, internals/daemon/api_health_test.go
This PR adds a new "health" command to Pebble. The health command queries the health of configured pebble checks. It outputs "healthy" and returns an exit code of 0 if all the specified checks are healthy. Otherwise, it outputs "unhealthy" and returns with an exit code of 1.
The "health" command accepts _~~two~~_ **one** option with arguments:
- The --level option takes an argument, either "alive" or "ready". It queries the health of only those checks with the same level. Note that, ready implies alive. Thus, if the ready checks are healthy but one of the alive checks is not, the overall output will be "unhealthy".
Usage:
pebble health [health-OPTIONS] [<check>...]
This PR includes a few tests too for the relevant changes.
---
This command does not add any new logic to Pebble, as it …
=> feat: add "health" command

internals/overlord/overlord_test.go, internals/overlord/state/export_test.go, internals/overlord/state/notices.go, internals/overlord/state/notices_test.go, internals/overlord/state/state.go
This implements the core state aspects of Pebble Notices -- spec [JU048](https://docs.google.com/document/d/16PJ85fefalQd7JbWSxkRWn0Ye-Hs8S1yE99eW7pk8fA/edit).
The key user-visible methods are `State.AddNotice` to add a new notices, `State.Notices` and `State.Notice` to fetch and filter existing notices, and `State.WaitNotices` to wait (or long-poll) for notices as they occur.
The follow-on changes are in separate PRs for easier review:
* The notices API: `/v1/notices` and `/v1/notices/{id}` -- #296
* The Go client for notices -- #297 
* The CLI: `pebble notices`, `pebble notice`, and `pebble notify`) -- #298 
* Recording `change-update` notices whenever a change is spawned/updated - TODO
* Using notices to implement warnings (notices are basically a superset of warnings) - TODO
=> feat(state): add core support for Pebble Notices

internals/daemon/api_notices.go, internals/daemon/api_notices_test.go
During code review of #296, when I'd switched the add-notice API endpoint to use `json.RawMessage` for the data field, it no longer handled the case where the data field wasn't present (which is perfectly valid if you don't have data to attach). This made `pebble notify` fail like so:
```
$ pebble notify example.com/fizzbuzz
error: cannot decode notice data: unexpected end of JSON input
```
However, it does this work if you provide one or more data keys/values:
```
$ pebble notify example.com/fizzbuzz kee=valyou
Recorded notice 1
```
This PR is a trivial fix for the (first) no-data case, and also adds a test case for the no-data case.
=> fix(daemon): add-notice API shouldn't error if no data is provided

internals/overlord/state/notices_test.go, internals/overlord/state/state.go
With the addition of support for notices in the pebble state, there was a small bug introduced in `ReadState`, which was not updated to set the new `noticeCond`. As a result, a call to `WaitNotices` from a state which was created via `ReadState` will cause a null pointer exception.
This PR adds the proper `noticeCond` initialization in `ReadState`, as well as a unit test to check that `WaitNotices` does not panic on a state which was created via `ReadState`.
=> fix(state): set `noticeCond` correctly in `ReadState`

.github/workflows/snap.yml, snap/snapcraft.yaml
Reopen of: #316 using a branch on this repo, rather than a fork, in order to test CI.
=> fix(snap): make snapcraft.yaml compatible with remote-builds

README.md
This commit adds the Snapcraft.io Github badge to the README of Pebble.
This has two benefits:
- People will immediately see that they can play with Pebble by installing it as a snap
- The repo will be picked up by https://releases.juju.is where we'll be able to tie snap revisions to commits etc.
Driveby to remove the "cute" tagline.
=> docs: add snapcraft badge to README

.github/workflows/snap.yml
The snap workflows can't currently run for PRs created from forks, since the repo's policy is not to allow forks to access any secrets.
The caveat here is that, for PRs, we won't be able to assert if the snap can build for architectures other than the GH's `runner.arch`. I don't think there's a way around this since the multi-arch build relies on LP, and for that we always need credentials. 
To be fair, the same would happen if we still had the Snap store connected to this repo, since the multi-arch builds would also only happen on `push` to `master`.
The snap.yaml workflow builds the snap with basis on the type of event triggering the workflow:
- for PRs, the snap build will only take place for `amd64`, and use `snapcraft pack`
- for every other event (`push` and `release`), the snap …
=> fix: allow local building and testing of the snap on PRs

internals/daemon/api_notices.go, internals/daemon/api_notices_test.go
Invalid notice types are ignored when parsing the API request to construct the notice filter. However, if only invalid notice types are included in the request, discarding all types results in a filter indistinguishable from one which never had any types in the first place, and thus would return notices of any type. This commit fixes this behaviour, so no notices are returned if only invalid notice types are requested.
=> fix(daemon): handle invalid notice types in filter

README.md
This section is now basically all done, so seems a bit pointless. We have GitHub issues for feature requests / upcoming work, and the commit history and Releases page for past work.
=> docs: remove Roadmap/TODO section in README.md

internals/testutil/containschecker.go, internals/testutil/containschecker_test.go, internals/testutil/errorischecker.go, internals/testutil/errorischecker_test.go
This PR is made in preparation to merge the latest snapd state package changes into pebble as per the plan discussed in https://github.com/canonical/pebble/pull/259. 
Both ErrorIs and DeepUnsortedMatches checkers are used by the latest state package test suites. These are cherry-picked from the snapd repository with some minor changes (fixed Pebble linter's warnings, updated license header).
=> feat(testutil): add ErrorIs and DeepUnsortedMatches checkers

internals/cli/cmd_run.go, internals/daemon/api_test.go, internals/daemon/daemon.go, internals/daemon/daemon_test.go, internals/overlord/managers_test.go, internals/overlord/overlord.go, internals/overlord/overlord_test.go, internals/overlord/stateengine.go, internals/overlord/stateengine_test.go
This PR introduces the StateStarterUp interface alongside its implementations for Overlord and StateEngine.
These changes were ported and adopted for pebble from the original snapd PR: https://github.com/snapcore/snapd/pull/7132
See also: https://github.com/canonical/pebble/pull/327
=> feat: add StateStarterUp to move expensive init ops to dedicated methods

.github/workflows/snap.yml
The current `if: github.event_name == 'push'` doesn't seem to be enough to make the `release` job run on `push`. I'm not entirely sure why this is, but I suspect it is because of its dependency's (`test`) run conditions.
This change makes the `release` run conditions explicit, instead of relying on the implicit behavior of `needs: [test]`.
=> fix: snap release job run condition

internals/daemon/api_notices.go
Most importantly, wait to lock the state until after the optional duration has been parsed, in case an error occurs. Also, moves the types query parsing/sanitization into its own function, since this cleans up the GET notices handler and better matches future handling of user ID filtering.
These changes were requested by @Meulengracht while reviewing the PR to merge the pebble notices API into snapd: https://github.com/snapcore/snapd/pull/13364
=> fix(daemon): small refactor of notices api

README.md, internals/cli/cmd_run.go, internals/daemon/daemon.go, internals/daemon/daemon_test.go, internals/overlord/restart/restart.go, internals/overlord/servstate/handlers.go, internals/overlord/servstate/manager_test.go, internals/plan/plan.go, internals/plan/plan_test.go
This PR makes Pebble shutdowns due to `on-failure: shutdown` return exit code 10 instead of always returning exit code 0. The code 10 was chosen to keep it "a few away" from other Pebble exit codes.
Similarly, if `on-check-failure` is used with `shutdown`, return exit code 11 instead of always returning code 0. (The 11 to distinguish a "check failure" shutdown from a "service failure" shutdown.
It also adds support for `on-failure: success-shutdown` (also for `on-check-failure`) and `on-success: failure-shutdown`, which reverses the "polarity" of the exit code for those cases.
Both of these are as per spec [DA062](https://docs.google.com/document/d/1OYSjmL2_1Na9HTwYmYo4KWvlQC9fcusXdMPzpHRBP8k/edit).
Fixes #324.
=> feat: make shutdown action return meaningful exit code

.github/workflows/snap.yml
The GitHub action used to download the snap artefacts was pulling the snaps from the previous workflow run instead of the current one. This commit changes the GitHub action and pulls all the snaps at the same time.
Example of a successful run: https://github.com/cjdcordeiro/pebble/actions/runs/7044673222
=> fix(snap): ensure snaps are from current run

README.md
As a follow-up to https://github.com/canonical/pebble/pull/323, update README.md to accurately reflect the addition of per-user notices.
=> docs: update readme notices section for per-user notices

.github/workflows/snap.yml
At the moment, the Pebble release process involves a series of 3 commits in a very short amount of time. GitHub's concurrency flag is being used to cope with this, but it is unable to wait for pending workflow runs (see the [bug](https://github.com/orgs/community/discussions/41518)), which raises the risk of a Release workflow cancelling the previous commit workflow, where the snap is being built, if the run is pending, waiting for a GH runner.
This commit forces the snap build to happen on releases also.
---
This change has been tested in https://github.com/cjdcordeiro/pebble/actions/runs/7221185730 (for regular pushes to `master`) and https://github.com/cjdcordeiro/pebble/actions/runs/7220657549 (for releases)
=> ci(snap): cope with concurrent builds

internals/daemon/api_notices_test.go
Improve the test coverage of the notices API, and on the behavior of per-user notices in particular.
This is a backport of a fix from the snapd port of pebble notices. The original commit can be found at:
https://github.com/snapcore/snapd/pull/13434/commits/027ae88e2e57e6d930c142c890e419ae362db70c
=> tests(daemon): improve test coverage of notices API

internals/daemon/daemon.go, internals/daemon/daemon_test.go, internals/overlord/export_test.go, internals/overlord/overlord.go, internals/overlord/overlord_test.go, internals/overlord/patch/patch.go, internals/overlord/restart/restart.go, internals/overlord/restart/restart_test.go, internals/overlord/servstate/handlers.go, internals/overlord/state/change.go, internals/overlord/state/change_test.go, internals/overlord/state/export_test.go, internals/overlord/state/notices_test.go, internals/overlord/state/state.go, internals/overlord/state/state_test.go, internals/overlord/state/task.go, internals/overlord/state/task_test.go, internals/overlord/state/taskrunner.go, internals/overlord/state/taskrunner_test.go, internals/overlord/state/warning.go, internals/overlord/state/warning_test.go
There are several major changes to the state package:
* Add WaitStatus support that allows a task to wait until further action to continue its execution. The WaitStatus is treated mostly as DoneStatus, except it is not ready status.
* Add Change.AbortUnreadyLanes.
* Add Change.CheckTaskDependencies to check if tasks have circular dependencies.
* Add task and change callbacks invoked on a status change.
* Update clients of the State.Get to use a new NoStateError to check if a desired key is present.
* Take StartOfOperationTime as a Prune parameter.
=> chore(state): cross-port latest changes from snapd's overlord/state

internals/daemon/api_notices.go, internals/daemon/daemon.go, internals/daemon/ucrednet.go, internals/daemon/ucrednet_test.go
This ports https://github.com/snapcore/snapd/pull/10126 from snapd, so that `ucrednetGet()` has the same return type.
This change is in preparation for porting the `accessChecker` API from snapd (https://github.com/snapcore/snapd/pull/10127): #358
=> daemon: make ucrednetGet() return *ucrednet

internals/daemon/daemon.go, internals/overlord/servstate/handlers.go, internals/overlord/servstate/manager.go
In most cases we're just reading from m.plan fields (Services,
DefaultServiceNames, and so on), so we can use m.Plan(), which holds
the plan lock only for the duration of fetch m.plan -- this is safe,
because we never mutate what's inside m.plan, we only replace it (in
updatePlan).
This also means that in functions like Services() we're only holding
either the plan lock or the services lock at once, not both -- avoiding
the 3-way deadlock described in #314.
For the cases we are updating the plan (AppendLayer, CombineLayer,
SetServiceArgs), we still need acquirePlan.
In ServiceManager.ServiceLogs, we don't need to acquire the plan lock
at all (m.plan isn't used).
Fixes #314.
=> fix(servstate): reduce scope of holding ServiceManager.planLock

internals/daemon/api_services_test.go, internals/overlord/servstate/handlers.go
This avoids the 3-lock deadlock described in
https://github.com/canonical/pebble/issues/314. Other goroutines
may be holding the state lock and waiting for the services lock, so
it's problematic to acquire both locks at once. Break that part of the cycle.
We could do this inside serviceForStart/serviceForStop by manually
calling Unlock() sooner, but that's error-prone, so continue using defer,
but have the caller write the task log (which needs the state lock) after
the services lock is released.
This is in preference to the more invasive change in https://github.com/canonical/pebble/pull/356
=> fix(servstate): don't hold both servicesLock and state lock at once

internals/daemon/daemon.go, internals/daemon/daemon_test.go
As part of working on #358, we found out that the untrusted socket is not used, and so can be removed (in preparation for porting the `AccessChecker` changes from snapd in https://github.com/canonical/pebble/pull/358).
**Indicators that it's not used:**
If we look at how `canAccess` works, if we match on `untrustedSocketPath` (`isUntrusted`), the only way for `canAccess` to allow the request is when `c.UntrustedOK` is `true` (otherwise it unconditionally returns `accessUnauthorized` immediately):
```golang
if isUntrusted {
if c.UntrustedOK {
return accessOK
}
return accessUnauthorized
}
```
So in order for any API calls to be allowed with the untrusted socket (assuming all API calls go through `canAccess`), we would need to have a `Command` defined with `UntrustedOK: true`. Checking the …
=> chore(daemon): remove untrusted socket

internals/daemon/api_changes.go, internals/daemon/api_checks.go, internals/daemon/api_exec.go, internals/daemon/api_files.go, internals/daemon/api_health.go, internals/daemon/api_logs.go, internals/daemon/api_notices.go, internals/daemon/api_plan.go, internals/daemon/api_services.go, internals/daemon/api_signals.go, internals/daemon/api_tasks.go, internals/daemon/api_warnings.go, internals/daemon/daemon.go, internals/daemon/response.go
This brings the error response namings in line with snapd: [`daemon/errors.go` in snapd](https://github.com/snapcore/snapd/blob/489358223f0bd03da01e62a4062174eb7e9e0ffa/daemon/errors.go#L112). Split off from #358. While currently the error responses are used exclusively in the `daemon` package, once `AccessChecker` is available, it should be possible for other packages to create error responders to implement their `AccessChecker` variants.
=> fix(daemon): Export error responders from daemon.response

README.md, internals/overlord/state/notices.go, internals/overlord/state/warning.go
See comment in `warning.go` for details.
=> doc(state): say why we're not implementing warnings as notices yet

.gitignore, internals/overlord/servstate/manager.go, internals/overlord/servstate/manager_test.go, internals/plan/plan.go, internals/plan/plan_test.go
This PR moves layer/plan validation into dedicated functions, with `Layer.Validate` covering validation that is specific to a layer (such as an invalid value) and `Plan.Validate` covering validation that covers the plan as a whole (such as cycles or missing values).
Plan validation includes layer validation, and is done in the service manager's `updatePlanLayers` and in `plan.CombineLayers`.
We also use the check period as the upper bound for the timeout in checks, which was happening before, but less explicitly.
No additional validation is done - all of the validation code is moved rather than changed.
Fixes #349
=> fix: validate whole plan, rather than topmost two layers

README.md, internals/cli/cli.go, internals/cli/cmd_run.go, internals/cli/cmd_run_test.go, internals/cli/copyfs.go, internals/cli/export_test.go
`$PEBBLE_COPY_ONCE` environment variable allows `pebble run` to copy layers and state from another directory when seeding a new `$PEBBLE` directory.
The rationale for this change is to allow OCI images to specify existing layers in the default `$PEBBLE` location. Then at runtime, be able to run `pebble` with a different `$PEBBLE` directory. This allows `pebble` to be run as a non-root user or run on a read-only root filesystem.
Issue #351 outlines that `pebble run` has no unit or integration tests. A test should be performed manually for now.
Manual QA is as follows:
- Create a directory, with a layers subdirectory and valid testing layers (e.g. ~/dir/with-existing-state)
- Create another empty directory. (e.g. ~/dir/with-no-state)
- `PEBBLE_COPY_ONCE=~/dir/with-existing-state …
=> feat(daemon): Add support for `PEBBLE_COPY_ONCE`.

client/notices.go, client/notices_test.go, internals/cli/cmd_notices.go, internals/cli/cmd_notices_test.go, internals/daemon/api_notices.go, internals/daemon/api_notices_test.go
This is a backport of a fix from the snapd port of pebble notices. The original PR can be found at:
https://github.com/snapcore/snapd/pull/13630
As snapd lacks a client or cli for notices, this commit also replaces "select" with "users" in the pebble client and cli.
=> fix(notices): replace "select=all" with "users=all"

internals/daemon/api_health.go, internals/daemon/api_health_test.go, internals/overlord/state/state.go
This PR avoids acquiring state lock in health check endpoint, a localised fix for the issue described in https://bugs.launchpad.net/juju/+bug/2052517 and #366.
I don't love the addition of the (exported) State.LockCount method, but I couldn't think of another way to ensure that State.Lock was not being called, apart from significant surgery allowing us to swap out the state lock with an interface.
In addition, I'm not sure we need the maintenance/warnings stuff at all in Pebble, as they're not used, but leaving that for a separate discussion and PR.
I tested by saving the script https://go.dev/play/p/LJDLEaXeBpd to cmd/hithealth/main.go, running a Pebble server, and then running a task to heavily load my CPU cores (though the latter doesn't seem to make much of a difference!).
Without the …
=> fix(daemon): avoid acquiring state lock in health check endpoint

internals/daemon/api_notices.go, internals/overlord/state/notices.go
This confused me when I was looking at locking stuff recently -- make it clear that `WaitNotices` releases the state lock (via the `sync.Cond`).
=> docs: add comments to clarify that WaitNotices releases the state lock

internals/overlord/state/change.go, internals/overlord/state/change_test.go, internals/overlord/state/state.go
This PR records change-update notices based as mentioned in the [JU048](https://docs.google.com/document/d/16PJ85fefalQd7JbWSxkRWn0Ye-Hs8S1yE99eW7pk8fA/edit) spec.
- `NewChange` addresses the change spawned case.
- `notifyStatusChange` is for all other status changes.
This is backport from snapd snapcore/snapd#13528.
=> feat(state): record change-update notices on change status updates

internals/cli/cmd_run.go, internals/daemon/api_exec_test.go, internals/daemon/api_test.go, internals/daemon/daemon.go, internals/daemon/daemon_test.go, internals/overlord/servstate/manager.go, internals/overlord/servstate/manager_test.go, internals/systemd/systemd.go
For example, if an exec command is running when you Ctrl-C the Pebble daemon, it hangs.
It's hanging because the ServiceManager is stopping the reaper early in the process, before TaskRunner has had a chance to abort the exec tasks (aborting an exec task sends SIGKILL to its pid via the tomb and command context).
Then when TaskRunner.Stop is called, it calls tomb.Kill and then tomb.Wait on each task (exec) tomb, and because the reaper's not running, the tomb.Wait hangs.
So the fix is to move the reaper.Start and reaper.Stop to the top level (inside the "run" command, which is also used for "enter"), instead of putting them in servstate.NewManager and ServiceManager.Stop.
After doing this, some of the tests also had to be modified to start and stop the reaper.
Fixes …
=> fix: start process subreaper at top level to avoid shutdown hangs

internals/daemon/daemon_test.go, internals/systemd/systemd_test.go, internals/testutil/exec.go, internals/testutil/exec_test.go, internals/testutil/export_test.go
Partly due to the fact that Pebble acts as a child subreaper, running additional commands outside the reaper is problematic. The "withReaper" argument to FakeCommand is a case in point.
However, instead of refactoring tests and FakeCommand to be reaper-aware, let's just remove the "maybe shellcheck" thing altogether.
I think it's problematic to have tests *maybe* do something if a specific command ("shellcheck" in this case) is installed on the system: some developers will catch issues with shellcheck, others won't. Plus, this has never caught anything for me in my Pebble journeys.
It also adds about 1s to the test running time, though that's not the main reason I want to take it out.
For reference, [here](https://github.com/snapcore/snapd/commit/a1f3919502da59a9cf331e3a7d10d5269dcf64bd) …
=> refactor: remove maybeShellcheck from FakeCommand

client/logs.go, client/logs_test.go
The server caps lines at 4096 characters, but the client receives these as JSON, so when receiving there's an extra ~70 characters that make up the timestamp, service name, field names, and JSON punctuation. This means that limiting the slice size to 4096 characters there will result in buffer full errors.
Allow an extra 1024 characters for the JSON 'overhead' - this should be far more than needed, but is only used within the `logs` function - I wasn't able to find any maximum length for a service name, so a precise extra count is tricky. This could be lowered (I would guess 128 characters would usually be sufficient) if this might be too much memory in some Pebble use cases.
Also adds tests for the long log line cases.
Fixes #376
=> fix: allow for the JSON overhead when reading log lines

client/client.go, client/client_test.go
I noticed that `pebble notices --timeout=60s` was taking about 5s to exit after you pressed Ctrl-C, when we were listening to SIGINT correctly and cancelling the context. Turns out `defaultRequester.retry` was only looking at the timeout channel, not the `ctx.Done()` one.
Writing this afresh we'd probably just use a context for the timeout as well as for cancellation, but do this minimal fix for now.
=> fix(client): make retry loop stop immediately when context is cancelled

internals/cli/cmd_run.go
PR #380 recently changed the way the reaper is stopped.
If `runDaemon()` returns an error the `defer` method overwrites the `err` return value in `err = reaper.Stop()`. If `err` was already set to something else, this will in effect overwrite the non-`nil` `err` with either `nil` (if `reaper.Stop()` returns `nil`) or a different error (if `reaper.Stop()` returns a different error).
Currently (without this PR):
- `err == nil` on defer method entry, `reaper.Stop()` returns `nil` - that's okay (no error)
- `err == nil` on defer method entry, `reaper.Stop()` returns non-`nil` - that's okay (reaper error reported)
- `err != nil` on defer method entry, `reaper.Stop()` returns `nil` - `err` overwritten, `runDaemon` errorneously returns success
- `err != nil` on defer method entry, …
=> fix(run): don't overwrite err on reaper.Stop()

internals/cli/cmd_run.go, internals/cli/cmd_run_test.go
If the `PEBBLE_COPY_ONCE` source directory does not exist, it will fail to copy inside the borrowed std go copyFS function. This adds an `os.Stat` to check if it first exists, ignoring it otherwise (the expected behavior).
=> fix(cli): PEBBLE_COPY_ONCE on missing dir.

client/client.go
Properly pass the Host (`localhost` for UNIX domain sockets, the host and port values for TCP sockets) to the websockets library.
=> fix(client): use host from BaseURL for websockets

internals/daemon/api_notices.go, internals/daemon/api_notices_test.go
This is a subset of related changes made in snapd: https://github.com/snapcore/snapd/pull/13673
=> fix(daemon): deduplicate user-provided notice types

internals/cli/cmd_help.go
The commands `help` and `version` are not related to running the service manager (you can run `help` also for client help, and `version` prints both the client and the server version). This splits those two commands into a new "Info" category, leaving only the `run` command in the "Run" category.
=> feat(cli): new Info category for help, version

cmd/personality.go, cmd/version.go, internals/cli/cli.go, internals/cli/cmd_help.go
Just like `ProgramName` and `DisplayName` can already be customized via public vars in the `cmd` package, `DefaultDir` also looks like a perfect candidate to customize this way (and assembling the help text can then be done using `{{.DefaultDir}}`).
In addition, `cli.HelpHeader` and `cli.HelpFooter` are made public, so that they can be extended and overridden.
=> fix(help): DefaultDir to personality, allow overriding header and footer

internals/overlord/state/taskrunner.go, internals/overlord/state/taskrunner_test.go
This changes this log:
```
2024-03-21T06:37:37.224Z [pebble] [change 32 "Start service \"svc1\"" task] failed: cannot start service: exited quickly with code 1
```
To this, which is more consistent with the formatting of the other Pebble logs:
```
2024-03-21T06:43:09.559Z [pebble] Change 33 task (Start service "svc1") failed: cannot start service: exited quickly with code 1
```
This log was introduced in this commit:
https://github.com/canonical/pebble/commit/e494ff2eed86799ce5756ae02f9442b890c3472f#diff-e8b7c8da8654dde95838cfa0cc4b497cdd32050ea3a1bf0640e6404303aef0d6R294 which was pulled across from snapd, which originally added it here: https://github.com/snapcore/snapd/commit/8b2a5a8b9b62408e4d549fde3d231f2775dce3b9
=> fix(taskrunner): consistent, nicer formatting for task failed log

internals/daemon/api_health.go, internals/daemon/api_health_test.go, internals/overlord/state/state.go
As Harry pointed out at https://github.com/canonical/pebble/pull/369#discussion_r1505423350, there's a much simpler way to test this without needing a new State method like LockCount. Just acquire the state lock, then call the endpoint. If it times out, we know it was trying to acquire the lock.
In addition, fix an issue where the health endpoint would still hold the state lock if it returned an error. Fix those and add a test for that too.
As far as I'm concerned, this additional fix isn't critical to ship out right away, as it's extremely unlikely the health check endpoint returns an error. It can just go out in the next version of Pebble.
=> fix(daemon): improve health state lock test, remove LockCount

client/notices.go, client/notices_test.go
Just the addition of the constant.
This was missed earlier when adding the change-update notice.
=> feat(client): add change-update notice type

internals/overlord/planstate/manager.go, internals/plan/plan.go, internals/plan/plan_test.go
Making layers with label "pebble-*" reserved for pebble use only.
Closes https://github.com/canonical/pebble/issues/220.
Test:
```$ tree $PEBBLE
/home/ubuntu/PEBBLE_HOME
└── layers
└── 001-pebble-test.yaml
1 directory, 1 file
$ go run ./cmd/pebble run
cannot run daemon: cannot load plan: cannot use reserved layer label "pebble-test"
exit status 1
```
=> feat: make layers with label prefix "pebble-" reserved

client/changes.go, client/changes_test.go
Add client-side validation for change ID used in URLs.
Closes https://github.com/canonical/pebble/issues/318.
=> feat: client side change id validation

README.md, client/notices.go, internals/daemon/api_notices.go, internals/overlord/state/notices.go
Also use consistent "/path" to indicate it can be a path (with multiple segments).
This is per Tony's comment at https://github.com/canonical/operator/pull/1170#discussion_r1550998027
=> chore: use RFC2602 domain (example.com) in custom notice examples

internals/overlord/checkstate/manager.go
Addresses https://github.com/canonical/pebble/issues/414.
Running checks have changes that get persisted by the state-engine. This means that following a reboot, changes and tasks that are not complete (not ready) will be resumed. In the case of some managers, such as checkstate, carryover changes and tasks are an unwanted side effect.
Currently the plan manager will perform the first plan load very early during startup (before the state-engine is ready, and before StartUp hooks have been called). The result is that a PlanChanged propagation will take place at plan load, and force checkstate to inspect the running checks prematurely.
Checkstate discovers a running change from a previous boot context, and tries to load its data from cached state, which does not exist.
Gracefully ignore …
=> fix(checkstate): ignore and abort carryover changes

cmd/personality.go, internals/daemon/daemon_test.go, internals/overlord/overlord.go, internals/overlord/overlord_test.go
Make it possible to customize the state file name, which is part of the personality (application name, pebble dir, ...).
=> feat(personality): Allow state filename customization

internals/cli/cmd_mkdir.go
`mkdir -p` (and the underlying API) has also worked this way, this just brings the help string up to date.
=> fix: note exist-ok behaviour of "mkdir -p" in argument help

.github/workflows/snap.yml
Fixes https://github.com/canonical/pebble/actions/runs/9392436751/job/25867410242
Recent [CI runs](https://github.com/canonical/pebble/actions/runs/9392436751/job/25867410242) started failing as Snapcraft is no longer considering the legacy location for Launchpad credentials, "$XDG_DATA_DIR/snapcraft/provider/launchpad/credentials".
This PR changes the snap.yml such that it now uses "$XDG_DATA_DIR/snapcraft/launchpad-credentials" instead.  
Reference: https://git.launchpad.net/snapcraft/commit/?id=83b67923d11200bc8dd8e75ec46df2644d70659d
=> fix: avoid legacy Snapcraft location for LP creds

.github/workflows/tests.yml, internals/daemon/api_files.go, internals/daemon/api_files_test.go, internals/osutil/mkdir.go, internals/osutil/mkdir_test.go
Add a new `Chmod` flag to `MkdirOptions` so that an explicit `chmod` command is executed on all directories created by `osutil.Mkdir`.
Closes https://github.com/canonical/pebble/issues/372.
| **Tests**                               | **Before**                                                                                                                | **After**                                                                              |
|-----------------------------------------|---------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------|
| pebble mkdir  ~/normal -m 777           | umask set to 0022, result is 0755, _not the same as …
=> feat(osutil.Mkdir): add the chmod flag

internals/osutil/user.go
Per https://github.com/golang/go/issues/67912, under some circumstances (on my machine) user.Lookup isn't returning UnknownUserError when it should. So before this fix I get the following test failures:
```
$ go test ./internals/osutil
...
FAIL: user_test.go:44: userSuite.TestRealUser
user_test.go:71:
c.Assert(err, check.IsNil)
... value *errors.errorString = &errors.errorString{s:"user: lookup username guy: no such file or directory"} ("user: lookup username guy: no such file or directory")
...
```
And:
```
$ go test ./internals/daemon
...
----------------------------------------------------------------------
FAIL: api_files_test.go:1128: filesSuite.TestWriteErrors
api_files_test.go:1195:
checkFileResult(c, r.Result[4], pathUserNotFound, "generic-file-error", ".*unknown user.*") …
```
=> fix: work around issue with user.Lookup not returning UnknownUserError

internals/cli/cmd_enter.go, internals/cli/cmd_enter_test.go
**NOTE: do not merge until https://github.com/canonical/rockcraft/pull/495 is finalized.**
This PR blocks the usage of ``--verbose`` option in "enter" command whenever the "exec" subcommand follows. Thus, the following will result in errors:
pebble enter --verbose [enter-OPTS*] exec [exec-OPTS] <cmd..>
Everything else, however, are kept unchanged. So the following is okay:
pebble enter [enter-OPTS*] exec [exec-OPTS] <cmd..>
Note that `enter-OPTS*` refer to all "enter" options except `-v`, `--verbose`.
Resolves https://github.com/canonical/pebble/issues/339.
=> fix(enter): block --verbose for exec subcommand

internals/overlord/overlord.go, internals/overlord/planstate/export_test.go, internals/overlord/planstate/manager.go, internals/overlord/planstate/manager_test.go
Some listeners do quite a bit of stuff (check manager and log manager), and they're defined in packages external to the planstate package, so it's best to avoid holding our plan lock for the duration.
See [spec OP040](https://docs.google.com/document/d/1cmZ5FWz0efglDAxGRciY5GRyD6KfWJCOe-kjWl6auig/edit#heading=h.po9vomna3y7d).
Also:
- PlanManager doesn't use state and runner, so remove them
- Rename planHandlers to changeListeners to match AddChangeListener
=> fix(planstate): don't hold planLock while calling plan-changed listeners

README.md
`on-check-failure` is a map of check name to value, so this field doesn't have a default, you have to add keys and values to the map explicitly. I believe this incorrect text was just a copy 'n' paste error.
In addition, I've added a (hopefully-clarifying) paragraph and tweaked things a bit.
Fixes https://github.com/canonical/pebble/issues/439
=> docs: various improvements to "service dependencies" section

internals/overlord/state/identities.go, internals/overlord/state/identities_test.go, internals/overlord/state/notices_test.go, internals/overlord/state/state.go, internals/overlord/state/state_test.go
This adds code and tests for the state core of identities ([spec OP043](https://docs.google.com/document/d/1nASgUt-piV94i1cpFsbEPRk_xFbZt8AskgL97gh1Dgg/edit#heading=h.a291qhvyhsw3)).
There's a new `map[string]*Identity` in state, which is marshalled via `marshalledIdentity` to disk. The marshalling for API requests is done by the `apiIdentity` type -- these are separate to ensure that the API (default) `MarshalJSON` for `Identity` does not include secrets (in future when we have identity types that include secrets; there's only user-id for now). So that's why there's a few more types and a bit more boilerplate than is necessary right now.
The new public `State` methods are:
* `AddIdentities`: add new identities to the system
* `UpdateIdentities`: update existing identities in the system
* …
=> feat(state): core of reading/writing identities in state

snap/snapcraft.yaml
Although not shown in the CI (because Trivy is being run with `trivy fs`, which [doesn't consider the Pebble binary](https://aquasecurity.github.io/trivy/v0.24.4/vulnerability/detection/language/)), there currently is a reported CVE in the Pebble snap (CVE-2024-24790).
This CVE seems to have been fixed on newer versions of Go, but we are still using Go 1.20 to build the Pebble snap.
This PR bumps this build dependency to Go 1.22.
=> fix(snap): build snap with Go 1.22 to fix CVE-2024-24790

.github/workflows/snap.yml, snap/snapcraft.yaml
When doing a `snapcraft remote-build`, Snapcraft will create a copy of the project in Launchpad before running the snap build.
The **problem** is that Snapcraft seems to ignore tags while creating the copy of the project, which means the `go generate ./cmd` in the `snapcraft.yaml`'s `override-build` will never dynamically generate the right version.
This PR enforces the execution of `go generate ./cmd` as a pre-requisite for running the snap build. I.e., for both local and remote builds, `go generate ./cmd` must be run first, such that the `VERSION` and `version_generated.go` files are staged in the repo, prior to the snap build, such that the `override-build` script can simply rely on that information and thus ignore the missing Git refs in the LP's project.
=> fix(snap): set Pebble version before snap builds

internals/daemon/api_test.go, internals/daemon/daemon.go, internals/overlord/overlord.go, internals/overlord/overlord_test.go, internals/overlord/restart/restart.go, internals/overlord/restart/restart_test.go, internals/overlord/servstate/servstatetest/restart.go, internals/overlord/standby/standby_test.go
This is based on https://github.com/snapcore/snapd/pull/12166 (though the diff was applied more or less manually, as the patch couldn't be applied directly).
It includes the name changes to the restart.Handler interface methods.
=> refactor: pull in the snapd RestartManager refactoring

client/files.go, client/files_test.go
Currently the `Client.Pull` method is immediately checking the content type for multipart, but we should also check for a regular API error. This PR fixes that.
Before (in case of permission denied error):
```
$ pebble pull /etc/hosts hosts
error: expected a multipart response, got "application/json"
```
After:
```
$ pebble pull /etc/hosts hosts
error: access denied (try with sudo)
```
Fixes #413
=> fix: make Client.Pull properly handle API errors

internals/cli/cmd_run.go, internals/daemon/daemon.go
Daemon has a `.Dying()` method that mirrors the [`Tomb.Dying()`](https://pkg.go.dev/gopkg.in/tomb.v2#Tomb.Dying) API, but not `.Err()` for the [`Tomb.Err()`](https://pkg.go.dev/gopkg.in/tomb.v2#Tomb.Err) API. Add a `.Err()` pass-through function and print out the server exit reason for easier debugging should one of the daemon tomb goroutines die.
=> feat(daemon): add Err() to retrieve the tomb death reason

internals/reaper/reaper.go
Previously we weren't actually turning off child subreaping at the OS level in `reaper.Stop`, so it didn't reverse `reaper.Start`. Fix this, and also simplify the error handling a little.
This almost certainly didn't cause problems, because as soon as the Pebble process exits it doesn't matter. But it wouldn't have turned it off in tests, and it's just the Right Thing To Do.
Fixes #412
=> fix: actually turn off child subreaping in reaper.Stop

internals/daemon/api_services.go, internals/overlord/servstate/manager.go, internals/overlord/servstate/manager_test.go, internals/overlord/servstate/request.go, internals/overlord/servstate/request_test.go, internals/plan/plan.go, internals/plan/plan_test.go
When starting services, put services that depend on each other (before/after/requires) in the same lane. If there is no dependency, put it in a stand-alone lane. Tasks only wait for tasks defined in the same lane.
Fixes https://github.com/canonical/pebble/issues/231.
The logic is as follows:
- get services from plan so that before/after/requires can be fetched
- if a service doesn't depend on other services or isn't dependent by other services (it doesn't have before/after/requires, and it doesn't show up in other services' before/after/requires), put it in a single lane
- if a service has dependencies (before/after/requires), all these dependencies will be put in the same lane as the service itself
- tasks only wait for tasks of the same lane. Since the input is already sorted, the …
=> feat(plan): use lanes to start services with dependencies

internals/daemon/daemon.go, internals/overlord/overlord.go, internals/overlord/planstate/manager.go, internals/overlord/planstate/manager_test.go, internals/overlord/planstate/package_test.go, internals/plan/plan.go, internals/plan/plan_test.go
This allows having the layers directory in a different directory than the "layers" sub-directory inside the pebble directory.
The defaults are unchanged, but one can pass an optional non-empty string in `daemon.Options{LayersDir: ...}` when calling `daemon.New()` to use a custom location for the layers.
This also removes the need to pass `pebbleDir` into `plan` and `planstate`, as it really only needs the `layersDir`.
=> feat(daemon): allow overriding layers directory in daemon.Options

internals/overlord/stateengine.go, internals/overlord/stateengine_test.go
Currently managers are started and stopped in a FIFO (first in, first out) order, but I would expect managers to behave more like a stack, in that they are started and stopped in a LIFO (last in first out) order. So the stopping of the managers should be done in reverse.
See this image:
Why? Because what if manager M2 started after manager M1 depends on some functionality from M1? Stopping M1 before stopping M2 might lead to unexpected and undefined behavior.
I chose to implement this behavior with the `defer` keyword [as it behaves in a LIFO manner](https://go.dev/tour/flowcontrol/13), but this could also be done by reverse iterating over the slice. I found the `defer` approach to be more concise, but feel free to correct me.
@benhoyt could you please take a look at this and advise me if …
=> feat(overlord): reversed order of manager stop

internals/overlord/cmdstate/handlers.go, internals/wsutil/wsutil_linux.go
If the interactive mode is enforced in `pebble exec`, there are scenarios like:
```go run ./cmd/pebble exec -i -- tee < ./HACKING.md```
that would prompt the server to shutdown the execution earlier than the whole output from 'tee' will be read and sent to the client. Hence, instead of closing the master pty descriptor when there is no more input from the client, send
Ctrl-D (EOF) to indicate to the process that there will be no more input.
Fixes #306.
=> fix(overlord): send EOF to master pty in interactive mode

docs/tutorial/getting-started.md
Minor changes to the tutorial according to Anne's suggestion.
Closes https://github.com/canonical/pebble/issues/464.
This PR makes sure:
=> docs: update tutorial according to review

internals/overlord/cmdstate/handlers.go, internals/overlord/cmdstate/manager.go, internals/overlord/cmdstate/request.go
Per #411, the environment (and other task data) can get quite large for exec objects. Given that exec commands are one-shot and only relevant for the current run of Pebble, there's no need to persist them.
Note that none of this data is in "api-data" so it's not accessible via the API at all right now, and so this is a non-breaking change.
Later if we want to make exec tasks a bit more introspectable we can add the command line or other fields to "api-data" (but we shouldn't add the entire environment).
Fixes #411.
=> fix(cmdstate): don't store execSetup and environment in state

.github/workflows/tests.yml, docs/generate_command_docs.py, docs/reference/cli-commands/run.md, docs/reference/cli-commands/warnings.md
Minor fix to the automated doc generation.
Changes:
- When getting command help output, use `go run ./cmd/pebble`.
- GitHub Actions job to check if the automated CLI reference docs have been changed.
- Regenerate CLI command reference doc to fix `stty cols 80` issue.
=> chore: minor improvement to docs generation

internals/overlord/overlord.go, internals/overlord/state/state.go
Fix an issue where the Pebble daemon fails to start with a read-only file system.
Closes https://github.com/canonical/pebble/issues/462.
Changes:
- Check if Pebble dir is writable before creating the overlord state backend.
- Add some logging when backend writes fail to enhance user experience.
- Listen for interrupt signals when state unlock retries because of backend writes failure.
=> fix(overlord): pebble hangs with a read-only file system when starting the daemon

docs/index.md
Improve the definition of Pebble and add fundamentals.
In the current version, it only describes what Pebble can do, but most product docs start with defining "what it is", like `supervisor`, `runit`, etc, so I expanded the definition a little bit.
Also added a section as prerequisite. Maybe it is not necessary, please provide your feedback. I think it doesn't hurt because it has a few links to ubuntu.com.
Closes https://github.com/canonical/pebble/issues/465.
=> docs: enrich the landing page with basic concepts

docs/explanation/api-and-clients.md, docs/how-to/index.md, docs/how-to/manage-identities.md, docs/reference/identities.md, docs/reference/index.md
This adds docs for Identities:
* Access control information under "API and clients" - [preview](https://canonical-pebble--479.com.readthedocs.build/en/479/explanation/api-and-clients/)
* A "how to manage identities" guide - [preview](https://canonical-pebble--479.com.readthedocs.build/en/479/how-to/manage-identities/)
* And an "Identities" reference page to define/describe the concept - [preview](https://canonical-pebble--479.com.readthedocs.build/en/479/reference/identities/)
=> docs: add Identities documentation

internals/logger/logger.go, internals/logger/logger_test.go
When using a `logger.MockLogger()`, a background goroutine calling `logger.Noticef()` might race the underlying `bytes.Buffer` for read/write access. To avoid that, limit the returned buffer type for `MockLogger()` to just `fmt.Stringer` (and mutex-protect its reading from the buffer) as well as mutex-protect `Write()` calls to the underlying buffer.
To reproduce the race condition, run `go test -race ./internals/logger` with `TestMockLoggerReadWriteThreadsafe` added, but with the unmodified `MockLogger` implementation.
If more functions from `bytes.Buffer` are needed from the `MockLogger` return value, the interface can be expanded with additional pass-through lock-protected calls, but in all of Pebble, it seems only the `.String()` function is used, so only that is exposed for now. …
=> fix(logger): Make MockLogger threadsafe

docs/index.md
Update the "In this documentation" section on the main page.
Closes https://github.com/canonical/pebble/issues/480.
Changes:
- Add links to highlight important content for how-to, explanations and references.
Preview:
Some explanations of my experiments and how I arrived at this version:
- Tutorial: nothing has changed. I wanted to list the tutorial there like the LXD doc does, but since we have only one, it would look weird and the link would be the same as the section title's link, so I left this part untouched.
- How-to: all 3 existing how-to guides there. Since we only had 3, it doesn't make much sense to pick just 2 of the more important ones, so I listed them all.
- Explanations: only "General models" and "API and clients"; "Service dependencies" skipped because of duplication as …
=> docs: update in this documentation section

internals/overlord/checkstate/manager.go, internals/overlord/overlord.go
Managers can explicitly call ```state.EnsureBefore()``` if they wish to apply changes sooner than the scheduled 5min ensure overlord timer.
Although managers get a state instance at creation time, during ```overlord.New()```, it is currently forbidden to call ensure early on before the ```Daemon``` started the ```overlord.Loop()```. The current restriction stems from the fact that ```state.EnsureBefore()``` adjusts the ensure timer expiry time, and the timer is only created when ```overlord.Loop()``` is called.
**The problem:**
Since the overlord ensure loop is only started later on during ```daemon.Start()```, a manager has no direct way to know when it's safe to call Ensure. Managers currently have to use the first call to their ```Ensure()``` method as an indication the overlord loop …
=> fix(overlord): allow ensure when state is available

internals/daemon/daemon_test.go
`daemonSuite.socketPath` appears to be assigned outside of the test, but only when it has a default value, which results in a stale `socketPath` value in this test.
```go
>  github.com/canonical/pebble/internals/daemon.(*daemonSuite).TestAddCommand() ./internals/daemon/daemon_test.go:186 (PC: 0xc17eef)
181:	}
182:	
183:	func (s *daemonSuite) TestAddCommand(c *C) {
184:		const endpoint = "/v1/addedendpoint"
185:		var handler fakeHandler
=> 186:		getCallback := func(c *Command, r *http.Request, s *UserState) Response {
187:			handler.cmd = c
188:			return &handler
189:		}
190:		command := Command{
191:			Path:       endpoint,
(dlv) print s
("*github.com/canonical/pebble/internals/daemon.daemonSuite")(0xc0000d4b80)
*github.com/canonical/pebble/internals/daemon.daemonSuite {
pebbleDir: …
```
=> fix: initialize socketPath to prevent stale cache

internals/osutil/mkdir_test.go
Added two more test cases to improve test coverage.
If the path already exists but it's not a directory, a `syscall.ENOTDIR` error is expected.
=> test: improve osutil.mkdir test coverage

.github/workflows/tiobe.yaml
Once a month, send the latest code quality (including coverage) data to TIOBE for central storage.
=> ci: add a monthly (or on demand) TIOBE reporting workflow

internals/daemon/api_health.go, internals/daemon/daemon.go, internals/overlord/state/notices.go, internals/overlord/state/notices_test.go, internals/overlord/state/state.go, internals/overlord/state/state_test.go
This means that not every request/response needs to acquire the state lock, as shown by the removal of the custom response type in the /v1/health endpoint.
Note that there's a test, TestHealthStateLockNotHeldSuccess, that specifically tests that the state lock is not held during /v1/health requests. If we accidentally introduce locking again, that will fail.
Fixes #366.
=> refactor(state): avoid need for state lock in LatestWarningTime

internals/plan/export_test.go, internals/plan/extensions_test.go, internals/plan/plan.go, internals/plan/plan_test.go
The plan library was originally written as a configuration schema for the services manager (servstate). Over time the need arose to support configurations for other managers such as checks (checkstate) and log-targets (logstate). The configuration schema for these managers, closely related to the services manager, has since also been built in to the plan library.
The services manager and its related checks and log-targets functionality will always be part of the Pebble core. However, as Pebble is getting more functionality (additional managers) and also used as a core in derivative projects, a more modular and dynamic approach to extending the schema is needed.
Add an the ```SectionExtension``` interface for use by managers who wishes to register a schema extension during Pebble startup. …
=> feat(plan): add plan section support

internals/overlord/planstate/manager.go, internals/overlord/planstate/manager_test.go, internals/overlord/planstate/package_test.go
Built on top of https://github.com/canonical/pebble/pull/488.
Add section support to the Plan Manager (planstate).
=> feat(planstate): add plan section support

.github/workflows/tests.yml, internals/cli/cmd_add_test.go, internals/daemon/api_exec_test.go, internals/daemon/api_files_test.go, internals/osutil/io_test.go, internals/osutil/mkdir_test.go, internals/osutil/stat_test.go, internals/overlord/servstate/manager_test.go
Background: Previously, when adding a new root test, we had to modify the GitHub Actions workflow to include the newly added test, which is some extra operational overhead.
Per discussion [here](https://github.com/canonical/pebble/pull/500#issuecomment-2362290802), we agreed to run all tests with root and skip those tests that would fail with root (checking permissions and stuff), and this PR skips tests that would fail when running with root and made the GitHub Actions workflow for root tests much easier.
=> test: make root tests easier to run

SECURITY.md
Document the security policy for the Pebble project.
See also [SEC0026](https://docs.google.com/document/d/1RolsiWCWhM-sVmHFjLt-Mq5yKcgQJ8GLXssGJREjSL0/edit).
=> docs: add a security policy document

.github/workflows/scanning.yml
Known issue: https://github.com/aquasecurity/trivy-action/issues/389
Workaround: https://github.com/orgs/community/discussions/139074#discussioncomment-10808081
=> chore: vuln scan failure workaround

internals/servicelog/iterator.go, internals/servicelog/ringbuffer.go
Fix an issue where the ring buffer might deadlock because rwlock and iterator mutex are acquired in a different order.
Fixes: https://github.com/canonical/pebble/issues/508
Notes:
1. As discussed with Harry and Ben, `rb.Write` isn't adjusted because the rwlock and iterator mutex are acquired at different times.
2. Besides an internal `close` function, an internal `positions` function is created for the same reason.
3. The [test case here](https://github.com/canonical/pebble/issues/508#issuecomment-2409839516) is not added because it was supposed to be an easy way to reproduce the deadlock. Adding an additional benchmark test is not useful, and the deadlock issue can be caught by the `TestDeadlock` test case anyway.
4. All three functions `signalIterators`, `releaseIterators` and …
=> fix: ring buffer deadlock

client/plan.go, client/plan_test.go, docs/reference/cli-commands/add.md, internals/cli/cmd_add.go, internals/cli/cmd_add_test.go, internals/daemon/api_exec_test.go, internals/daemon/api_plan.go, internals/overlord/planstate/manager.go, internals/overlord/planstate/manager_test.go, internals/overlord/planstate/package_test.go, internals/overlord/servstate/manager_test.go, internals/plan/extensions_test.go, internals/plan/plan.go, internals/plan/plan_test.go
Pebble currently only supports loading configuration layer files from the root of $PEBBLE/layers.
Add support for adding sub-directory support at the root level (2 levels in total only). [Spec KO071.](https://docs.google.com/document/d/1-9GLCJTx9o_hSd0JGvDp7o5xNQjkJMvLam6o1Ba_bYM/edit?tab=t.0)
This scheme has an impact on the meaning of ```label``` and ```order```. See the following examples to understand the new mapping:
- $PEBBLE/layers/001-foo.yaml
Order: 001-000 => 1000
Label: foo
- $PEBBLE/layers/005-bar.d/010-abc.yaml
Order: 005-010 => 5010
Label: bar/abc
- $PEBBLE/layers/005-bar.d/012-def.yaml
Order: 005-012 => 5012
Label: bar/def
- $PEBBLE/layers/006-baz.yaml
Order: 006-000 => 6000
Label: baz
Directory support allows other uses of Pebble using read-only file systems more …
=> feat(plan): add plan sub-directory support

client/services.go
=> chore(client): fix typo in AutoStart doc comment

docs/tutorial/getting-started.md
In the getting started tutorial, mentioned that we need to run `pebble services` after `pebble stop http-server` if we want to view the service as inactive. This fixes #522.
=> docs: fix tutorial by including a status check after stopping http-server

internals/overlord/servstate/handlers.go
Set the `HOME` environment variable when only uid is set.
Closes https://github.com/canonical/pebble/issues/183.
The above issue could not be reproduced, because even if only "user" is set without "group", [Pebble will find and use the user's primary group](https://github.com/canonical/pebble/blob/master/internals/osutil/user.go#L117), and [when setting home, both uid and gid are not empty](https://github.com/canonical/pebble/blob/master/internals/overlord/servstate/handlers.go#L374).
The code change still feels right after a discussion with Tony and Dima in the standup, though, because setting HOME should have nothing to do with gid, empty or not.
On a probably unrelated topic: There is an unrelated issue (or feature) where [if user-id is used (instead of user), group-id must be …
=> feat: set home when user is set

docs/explanation/index.md, docs/how-to/index.md, docs/reference/cli-commands/cli-commands.md, docs/reference/index.md, docs/reference/pebble-in-containers.md
The purpose of this PR is to use a consistent style for the three landing pages [How-to guides](https://canonical-pebble.readthedocs-hosted.com/en/latest/how-to/), [Explanation](https://canonical-pebble.readthedocs-hosted.com/en/latest/explanation/), and [Reference](https://canonical-pebble.readthedocs-hosted.com/en/latest/reference/). How-to guides already has the style we want, so I'm using the same style for Explanation and Reference.
Summary of changes:
- **How-to guides** - Adjusted some wording for readability and consistency of language
- **Explanation** - Moved [General model](https://canonical-pebble.readthedocs-hosted.com/en/latest/explanation/general-model/) to the top of the TOC; split the landing page into sections with brief summaries
- **Reference** - Applied a logical …
=> docs: make landing pages more informative

docs/how-to/install-pebble.md
The purpose of this PR is to list the `pebble` snap as an option in [How to install Pebble](https://canonical-pebble.readthedocs-hosted.com/en/latest/how-to/install-pebble/).
Changes:
- Added a new section called "Install the snap" after "Install the binary". I put the new section immediately after "Install the binary" because these two sections are more user focused, whereas "Install from source" is more developer focused
- Adjusted some language within the page for readability and consistency
- Changed the link titles in "Install from source" to make it more obvious what we're linking to
=> docs: add snap as an installation method

internals/plan/plan.go, internals/plan/plan_test.go
If services are defined in random order in the layer config, for example, svc1, svc2, then svc3, but svc3 depends on svc1, when mapping these services into lanes, the maximum lane count is incorrectly calculated.
This PR fixes this issue and closes https://github.com/canonical/pebble/issues/525.
Manual test:
Layer config:
```yaml
summary: a simple layer
services:
test1:
override: replace
command: bash -c "sleep 1000"
startup: enabled
test2:
override: replace
command: bash -c "sleep 1000"
startup: enabled
test3:
override: replace
command: bash -c "sleep 1000"
startup: enabled
requires:
- test1
```
Result:
```bash
$ ./pebble run
2024-11-28T03:00:55.321Z [pebble] Started daemon.
2024-11-28T03:00:55.329Z [pebble] POST /v1/services 2.313041ms 202
2024-11-28T03:00:55.331Z [pebble] Service …
```
=> fix: mapping service to lanes when services are in random order

internals/timeutil/human.go
This has been added in upstream snapd back in the day here:
* https://github.com/snapcore/snapd/pull/4775
Move conditionals to the correct `case` where they belong (e.g. `>= -cutoffDays` belongs to the "%d days ago", ...), and then just naturally move the non-special case of `then.Format("2006-01-02")` to the `default` case.
Looking at compiler explorer, it seems like Go (gc 1.21 on x86_64) can optimize out the old version's `panic()`, so it's just dead code in the source (as it should be): https://godbolt.org/z/fxqTzYfPv
=> fix(timeutil): remove unreachable panic() call

docs/explanation/service-start-order.md, docs/reference/cli-commands/start.md, docs/reuse/service-auto-restart.md
Since [the PR for auto-restarting services that fail within okay delay](https://github.com/canonical/pebble/pull/520) is merged, we are updating docs that are related to the 1-second okay delay.
Note that the original [Service auto-restart](https://canonical-pebble--531.com.readthedocs.build/en/531/reference/service-auto-restart/) reference doc is not updated because the description in it is still valid, so I didn't update it.
[Here](https://canonical-pebble--531.com.readthedocs.build/en/531/) is a preview, please:
- Help check if I missed anything;
- and see if we can better organize the content in the [Service auto-restart](https://canonical-pebble--531.com.readthedocs.build/en/531/reference/service-auto-restart/) reference doc to address this change.
=> docs: update okay delay related docs

internals/daemon/daemon.go, internals/daemon/daemon_test.go
This patch adds a new `daemon.ExternalMode` reboot mode that does nothing, so that code in charge of starting and stopping the Pebble daemon can run custom logic after the daemon has stopped.
When `ExternalMode` is set and the Pebble daemon stops after a system restart has been requested, `daemon.Stop()` returns the special `daemon.ErrRestartExternal` error that can be detected by the caller in order to execute custom reboot logic.
Furthermore, the fallback reboot handler is set to `syscallModeReboot()`, so that a system reboot is forced after `rebootWaitTimeout` is reached. In other words, the code responsible for handling the reboot with custom logic has a time span given by `rebootWaitTimeout` to perform a system reboot, or it will be forced.
```go
func exampleUsage() error {
/* ... */ …
```
=> feat(daemon): add `ExternalMode` reboot

docs/index.md
This PR adds a new section called "Releases" to the docs homepage. The purpose is to help newcomers find the Pebble release notes.
Preview build: https://canonical-pebble--533.com.readthedocs.build/en/533/
(While making this change, I also removed a couple of trailing periods in the "Project and community" bullets, for consistency)
=> docs: add release info to homepage

docs/reference/cli-commands.md, docs/reference/layer-specification.md
A `replan` command will start any services that have been stopped (with a `stop` command), if the service has `startup: enabled` set. Clarify that in the documentation.
=> docs: clarify the replan behaviour with regards to stopped services

docs/explanation/api-and-clients.md, docs/reference/cli-commands.md, docs/reference/identities.md, internals/cli/cmd_run.go
The purpose of this PR is make it easier to understand details about API security. (I'll create a separate PR to add a general security overview doc)
Summary of changes:
* Specify which API endpoints have which access level
* Use terms more consistently:
* "Authenticated" to mean a user with `read` or `admin` access level
* "Unauthenticated" to mean a user with `untrusted` access level
* "Open-access" to mean an API endpoint that doesn't require authentication (instead of calling them "untrusted")
Preview build: https://canonical-pebble--535.com.readthedocs.build/en/535/
=> docs: clarify different types of API access

docs/explanation/index.md, docs/explanation/security.md
This PR adds a new page to summarize security considerations for Pebble. Preview: https://canonical-pebble--536.com.readthedocs.build/en/536/explanation/security/
=> docs: add an overview of security

docs/reference/api.md
This PR adds JavaScript code to create TOC entries for the sections (tags) in the API reference.
**[Preview build](https://canonical-pebble--542.com.readthedocs.build/en/542/reference/api/)**
**The tags need to be hardcoded in _api.md_.** It would be possible for JavaScript to determine the tags from the rendered Swagger UI elements, but there's no event to tell us when the Swagger UI has rendered. So I think it's not worth the effort - simpler to hard code the tags.
**Behavior**
- Adds a link for each tag inside the last top-level entry in the TOC.
- When a tag link is clicked (with no modifier keys), the tag section scrolls into view. The tag section opens if it's not open.
**Why do this in JavaScript?** We already run some JavaScript, because Swagger UI requires JavaScript. And even if …
=> docs: add API reference sections to the TOC

docs/.sphinx/_static/swagger-override.css, docs/specs/openapi.yaml
Adding more endpoints to the OpenAPI spec.
- Refactor existing endpoint parameter examples and remove them.
- Refactor existing request body examples, but keep only one.
- Refactor non-directly used component names as lowercase.
- Reorder API groups according to `pebble help` output.
- Similar to hiding the input box for parameters, hide the select drop-down (because one newly added endpoint has an enum).
- `/v1/system-info`. The code is [here](https://github.com/canonical/pebble/blob/master/internals/daemon/api.go#L122), and the possible boot-id value is [here](https://github.com/canonical/pebble/blob/master/internals/overlord/overlord.go#L243).
- `/v1/health`. The code is [here](https://github.com/canonical/pebble/blob/master/internals/daemon/api_health.go#L31).
- `/v1/changes`, code is …
=> docs: add more api specs

docs/.sphinx/_static/swagger-override.css, docs/reference/api.md, docs/specs/openapi.yaml
In this PR:
- Add 502 responses for `/v1/health` endpoint according to David's suggestion, because otherwise, people would think it's 200 even if healthy is false.
- Reformat multi-line descriptions.
- Change "examples" to "example" to make the spec shorter with less indentation
- Change the example to JSON format to make it less error-prone (no need to translate JSON response to YAML format in the spec).
- Rename component names to more appropriate ones because they will appear in the schema. Convention: `VerbResource[Description]Response`, for example, `GetPlanResponse`, `GetHealthOKResponse`.
- `/v1/plan`, [code](https://github.com/canonical/pebble/blob/master/internals/daemon/api_plan.go#L27).
- `/v1/layers`, [code](https://github.com/canonical/pebble/blob/master/internals/daemon/api_p …
=> docs: finish pebble http api specs

internals/cli/cmd_enter.go
Also change (2) text to add --verbose as well as just -v.
Fixes #551
=> docs: logs/-v no longer applies to "enter exec"

internals/osutil/export_test.go, internals/osutil/user.go, internals/osutil/user_test.go
This makes it valid to supply just the uid for operations setting file ownership, like mkdir and push.
This lack came up when investigating the API for the file operations library.
=> feat: support uid only form in NormalizeUidGid

client/changes.go, client/checks.go, client/client.go, client/client_test.go, client/exec.go, client/export_test.go, client/files.go, client/health.go, client/notices.go, client/plan.go, client/services.go, client/signals.go
Refactor client test framework to use the requester interface.
Closes https://github.com/canonical/pebble/issues/315.
See more information here in https://github.com/canonical/pebble/pull/310.
=> refactor: update client code+tests to use Requester interface

HACKING.md
This PR adds a few style tips to the Docs section of HACKING.md. I've tried to keep the list short and (hopefully!) memorable
=> docs: add doc style tips to HACKING.md

docs/index.md
The Diataxis categories in Pebble are currently ordered: Tutorial, How-to guides, Explanation, Reference. The standard order should be Tutorial, How-to guides, _Reference, Explanation_.
The 2x2 grid of cards on the homepage actually has the correct layout (matching the [Diataxis map](https://diataxis.fr/_images/diataxis.png)):
```
Tutorial     How-to guides
Explanation  Reference
```
This PR:
- Reorders the Diataxis categories to Tutorial, How-to guides, Reference, Explanation.
- Uses `:reverse:` in the grid source to swap Reference and Explanation, instead of ordering them as Explanation > Reference in the grid source. We need to do it this way so that Reference stacks above Explanation if the browser window is narrow.
In short, we're matching how Ops is set up. See …
=> docs: change Diataxis categories to the standard order

docs/reference/layer-specification.md, internals/overlord/checkstate/checkers.go, internals/overlord/checkstate/checkers_test.go
This was a bug. The code looks for any non-2xx HTTP status code, not just non-20x.
Also fix it in the layer reference doc and code comments.
=> fix: change "20x" in HTTP health check error messages to "2xx"

.github/workflows/binaries.yml, .github/workflows/snap.yml
[v3 of upload-artifact and download-artifact can no longer be used](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/). This PR bumps the version to v4.
For upload, v4 differs from v3 in that v3 would allow uploading multiple times with the same name and v4 does not. We do re-use the snapcraft-logs name - but only in failure, so I *think* this means that the workflow would exit before any clash occurred. We could adjust the names to avoid that possibility - I'm guessing that we only manually inspect them, rather than use the result in future work.
=> chore: bump the upload-artifact and download-artifact version

docs/requirements.txt
Primarily this pulls in security fixes for starlette, jinja, urllib3, and certifi, but it updates all the dependencies while we're doing this. The docs build with no errors and look ok with a cursory review.
=> chore: bump documentation dependencies

README.md
A quick PR to update the README to use the new URLs of Pebble docs. We've already set up redirects, so this is just to keep things tidy.
@benhoyt / @IronCore864 are you able to update the link in the **About** section of the repo? I don't think I have access to do that.
=> chore: update doc links in README

internals/daemon/api_checks.go, internals/daemon/api_checks_test.go
The PR changes the response to a `/v1/checks` POST to provide the list of names of started or stopped checks as sorted alphabetically.
A test is added to confirm this, which also tests the API post method more generally, which was missed in #560
This will also provide a sorted list of check names in the client (since it uses the API) and the CLI (since it uses the client). The *manager* continues to return the list of check names in the order in which they were started/stopped - this feels more correct to me (in terms of management, what matters is what happened; in terms of response to a request, convenience is important), but I could be convinced that the sorting should move up a level.
=> feat: sort the changed checks in the API response

docs/reference/cli-commands.md, docs/reference/environment-variables.md, docs/reference/index.md, internals/cli/cmd_enter.go, internals/cli/cmd_run.go, tests/enter_test.go, tests/main_test.go, tests/run_test.go
This PR adds a new environment variable "PEBBLE_VERBOSE", which if set to "1", Pebble will print service logs to Pebble's standard output. See [this spec](https://docs.google.com/document/d/1-NCelXSb4dVjZuEGDp_jsTnzV0idq6BXqZ4kGCkO9Nw/edit?tab=t.0) (internal only) for more details.
Summary:
- For `pebble run`, allow verbose logging mode (log all output from services to stdout) to be enabled when starting the daemon by setting the environment variable `PEBBLE_VERBOSE=1`.  This is equivalent to `pebble run --verbose`. Even if `PEBBLE_VERBOSE` is set to "0" explicitly, if the `--verbose` flag is still specified, the verbose logging mode is still enabled: the `--verbose` flag has higher priority.
- For `pebble enter exec`, the `--verbose` flag is currently disabled. However, `pebble enter` …
=> feat: verbose mode using environment variable

docs/how-to/use-layers.md, docs/reference/index.md, docs/reference/layer-specification.md
This PR adds intersphinx targets needed by https://github.com/canonical/operator/pull/1603. We haven't been entirely consistent with `-` vs `_` in targets in Pebble, so I've tried to be as consistent as possible:
- Use `-` for title targets
- Match the format of siblings for section targets
=> chore: add targets for links from Ops docs

internals/overlord/checkstate/handlers.go
This moves the logic inside each `ticker.C` case into an inner function. This is a reasonable change by itself, as it makes the for+select loop easier to read. It also reduces the indent one level. However, it's mainly in preparation for the new logic required for RefreshCheck (pebble check --refresh). See: https://github.com/canonical/pebble/pull/577/files
There shouldn't be any logic change here. I've simply replaced the `return`s to return `shouldExit==true` so the caller knows to return.
Note: the changes are *much* easier to review with [whitespace hidden](https://github.com/canonical/pebble/pull/582/files?diff=split&w=1) in GitHub.
=> refactor: move performCheck/recoverCheck logic into their own functions

docs/specs/openapi.yaml
This PR removes the lock icon and the authorize section in the rendered swagger UI:
After adding basic auth for the metrics endpoint, the Swagger UI renders an auth section that doesn't look nice or function properly. When clicked, it asks for a username and password, which would not work anyway since we don't have an API server.
Although adding the auth section means there is a lock logo on the `/v1/metrics` endpoint which is nice to have, it's not exactly necessary, because users need to read the descriptions about basic identities anyway. So, after a discussion with David, we decided to remove this.
[Current rendered result](https://documentation.ubuntu.com/pebble/reference/api/#api-endpoints), [metrics endpoint lock logo](https://documentation.ubuntu.com/pebble/reference/api/#/metrics) …
=> docs: remove openapi spec auth

snap/snapcraft.yaml
This PR improves the description that appears on the [Snap Store page](https://snapcraft.io/pebble) for Pebble.
Note that I removed mention of `SNAP_USER_DATA` by name, as that variable is not set outside of the snap. Outside of the snap, the most relevant point is that layer config is stored in `$PEBBLE/layers`, where `PEBBLE` is set to `$HOME/snap/pebble/<snap_revision>` by default.
=> docs: improve description for Snap Store listing

docs/explanation/security.md, internals/cli/cmd_run.go
Also add an example to the docs of how to tighten up this directly if it already exists.
=> fix: tighten permissions of --create-dirs directory from 0o755 to 0o700

docs/how-to/capture-logs-from-files.md, docs/how-to/index.md, docs/how-to/tail-file-logs.md
The proposal to add file tailing functionality directly to Pebble was rejected.
This PR documents the workaround.
=> docs: document how to tail file logs

docs/reference/cli-commands.md
The summary of commands at the top of the [CLI commands](https://documentation.ubuntu.com/pebble/reference/cli-commands/) page is missing `check`. This PR adds it.
**[Preview doc](https://canonical-ubuntu-documentation-library--608.com.readthedocs.build/pebble/reference/cli-commands/)**
=> docs: add 'check' to summary of CLI commands

docs/reference/cli-commands.md, docs/specs/openapi.yaml, internals/cli/cmd_run.go, internals/daemon/api.go, internals/daemon/api_test.go, internals/daemon/daemon.go
Per discussion on Matrix > Juju, we'd like to add the ability to get the HTTP port that Pebble is listening on (if any) to the /v1/system-info API response. This PR simply adds that field.
For example, if the Pebble daemon is started with `pebble run --http=:4040`, the API returns this:
```
$ curl --unix-socket /var/lib/pebble/default/.pebble.socket http://_/v1/system-info|jq
{
"type": "sync",
"status-code": 200,
"status": "OK",
"result": {
"boot-id": "30435cc9-b428-4e25-a821-c9477fc339eb",
"http-address": ":4040",
"version": "v1.21.0-dev"
}
}
```
=> feat: add http-address to /v1/system-info

docs/how-to/manage-a-remote-system.md
This PR adds a link to the Pebble specific charm management tips in the Juju docs, including the very ergonomic `jhack pebble` command.
Resolves #49.
=> docs: link to relevant Juju specific Pebble tips

docs/how-to/check-health-based-on-logs.md, docs/how-to/index.md, docs/how-to/run-services-reliably.md, docs/reference/health-checks.md
This PR adds a how-to guide called "How to check health based on logs". Closes #601
**[Preview doc](https://canonical-ubuntu-documentation-library--607.com.readthedocs.build/pebble/how-to/check-health-based-on-logs/)**
This PR also adds a couple of "see also" links after the examples on the health checks reference page ([see preview](https://canonical-ubuntu-documentation-library--607.com.readthedocs.build/pebble/reference/health-checks/#examples)).
=> docs: document how to check health based on logs

internals/cli/cmd_enter_test.go, internals/cli/cmd_run.go, internals/daemon/daemon.go, internals/idkey/idkey.go, internals/idkey/idkey_test.go, internals/idkey/package_test.go, internals/overlord/overlord.go
Add support for Pebble to have a machine, container or device identity that is based on an Ed25519 private key.
This identity key implements the crypto.Signer interface, allowing it to sign, for example, TLS certificates.
The identity key should eventually be stored in a hardware backed key-store, such as a TPM, OP-TEE or even YubiKey. The first implementation of the package implements disk based storage with restricted permissions, similar to what you would find when looking at your ~/.ssh directory.
The purpose of this package is to allow a machine, container or device to have a lifelong identity, including a standardized fingerprint that represents that identity. 
**Example use-case**
The identity private key can be used to sign short-lived TLS keypairs for the HTTPS Pebble API server, …
=> feat(idkey): add identity key [1/4]

docs/reference/cli-commands.md, internals/cli/cmd_run.go, internals/daemon/daemon.go, internals/daemon/daemon_test.go, internals/overlord/overlord.go
**Enable the API over HTTPS**
Pebble can now be started with the API enabled on HTTPS:
```
~/> ./pebble run --https=:8888 --http=:4000 --create-dirs
2025-04-08T15:14:40.523Z [pebble] HTTP API server listening on ":4000".
2025-04-08T15:14:40.524Z [pebble] HTTPS API server listening on ":8888".
2025-04-08T15:14:40.524Z [pebble] Started daemon.
2025-04-08T15:14:40.525Z [pebble] POST /v1/services 190.249µs 400
2025-04-08T15:14:40.525Z [pebble] Cannot start default services: no default services
```
The HTTPS (TLS) keypair is signed by the identity certificate (also included in the certificate chain from the server), so you need to connect with the client configured to allow for an untrusted connection.
The typical connection process will require a trust exchange step that allows the client to …
=> feat(https): add https API server [3/4]

internals/overlord/overlord.go, internals/overlord/state/notices.go, internals/overlord/state/notices_test.go, internals/overlord/state/state.go, internals/overlord/state/state_test.go, internals/overlord/state/taskrunner_test.go
When pruning changes, also prune notices under a few rules:
1) Remove Changes down to 1000 (changed from 500) according to the existing logic.
2) Remove "change-update" Notices that refer to changes that do not exist.
3) Further remove Notices down to 1000 Notices.
4) Log an aggregate result of what changes and notices have been pruned.
This is an update to https://github.com/canonical/pebble/pull/611, built off of 1.19.0. Some of the key differences to 611 are:
a) We prune all notices that refer to an unknown change, not just the ones that were recently pruned. This is better for consistency, and it means we don't need to track an extra set of what has changed.
b) Notices are also kept to an absolute maximum count.
I ran this with a lightly customized overload.go and state/notices.go to …
=> fix: when pruning changes preserve referential integrity for notices

docs/.sphinx/_static/swagger-override.css
Fix an issue when the page theme is set to "auto", but the system appearance is set to "dark", the Sphinx docs titles and background colour inversion (done in a previous PR to improve readability in dark mode) don't work properly.
After playing with it a bit and getting some help from @dwilding, we figured out that this only occurs when the page is set to auto and the system is set to dark, on both macOS and Ubuntu. If the user explicitly sets the colour theme to dark on the page, it works properly.
See more details [here in this issue](https://github.com/canonical/pebble/issues/614)
Closes https://github.com/canonical/pebble/issues/614.
Preview: https://canonical-ubuntu-documentation-library--617.com.readthedocs.build/pebble/reference/api/#/changes-and-tasks (Remember to set your system …
=> fix: page auto and system dark mode

HACKING.md
This PR adjusts the formatting of HACKING.md to resolve linting issues that will be caught by the latest doc starter pack (see #615).
@benhoyt I don't have a particularly strong opinion here, so I can find an alternative approach if you'd rather not do this.
=> chore: fix markdown issues in HACKING.md

docs/specs/openapi.yaml, internals/daemon/api.go, internals/daemon/api_test.go
When we added the `--https` option to `pebble run` (#599), we forgot to add the corresponding `https-address` field to the /v1/system-info response. Add that in now.
=> feat: add https-address to /v1/system-info response

client/client.go, client/client_test.go, client/exec.go, client/files.go, client/services.go
Add a default `Content-Type` header for the client requester. If not specified, use "application/json". It will be overridden when calling `client.Requester().Do` with headers set in `RequestOptions`. Also, remove the explicit Content-Type header with "application/json" in specific client calls.
Closes https://github.com/canonical/pebble/issues/561.
=> feat: add default Content-Type header to client requests

internals/overlord/checkstate/manager.go, internals/overlord/checkstate/manager_test.go
Calling change.Abort() is enough. We had previously added the SetStatus in commit f9250f69a92f297fb7f1bfbe16b145605ca71262 as the test was seeing a Hold status, but that was because it hadn't done an Ensure to actually move the checks to Doing. So fix the test as well, and the change should end up as Done.
Fixes #621
=> fix: avoid panic when Pebble restarts after stop-checks

client/checks.go, docs/reference/health-checks.md, internals/daemon/api_checks_test.go, internals/overlord/checkstate/handlers.go, internals/overlord/checkstate/manager.go, internals/overlord/checkstate/manager_test.go
This reverts PR #620 (commit d7127c9748f2cb56756242f186b3ab5589925bba) as it was too invasive. I had incorrectly assumed that charms weren't using the check status at this level, and it'd be okay to change. However, many charms use `get_checks()` and `CheckStatus.UP` or `.DOWN`, for example:
+ ranger-k8s-operator does get_check().status != CheckStatus.UP in update-status hook, sets MaintenanceStatus if so
+ temporal-ui-k8s-operator (similar)
+ trino-k8s-operator (similar)
+ sunbeam-charms (similar, but set BlockedStatus)
+ katib-operators (similar)
+ superset-k8s-operator (similar)
+ notebook-operators (similar)
The fact that they're comparing `!=UP` means these charms will now report a blocked or maintenance status in that initial "unknown" period before the check is run. And other …
=> fix: revert making checks report "unknown" before they've been run

client/checks.go, docs/how-to/check-health-based-on-logs.md, docs/reference/health-checks.md, docs/specs/openapi.yaml, internals/cli/cmd_check.go, internals/cli/cmd_check_test.go, internals/cli/cmd_checks.go, internals/cli/cmd_checks_test.go, internals/daemon/api_checks.go, internals/daemon/api_checks_test.go, internals/overlord/checkstate/handlers.go, internals/overlord/checkstate/manager.go, internals/overlord/checkstate/manager_test.go, internals/overlord/checkstate/request.go, internals/overlord/servstate/handlers.go
This adds a "Successes" column to the output of `pebble checks` (and field to the `pebble check` YAML), as well as a "successes" field in the `/v1/checks` API response.
"Successes" is the number of times this check has succeeded. It is reset when the check succeeds again after the check's failure threshold was reached. It will be zero if the check has never run, or has never run successfully. If successes==0 and failures==0, the caller knows the check has not yet been run.
The client field `CheckInfo.Successes` is typed as a pointer (`*int`) as it's being added in a much later version of Pebble -- this means clients will be able to tell the difference between `*Successes==0` and `Successes==nil` (nil meaning the field is not present in the API response because they're querying on older …
=> feat: add "successes" field to checks API and CLI output

docs/how-to/service-dependencies.md
I noticed that the last sentence of [How to manage service dependencies](https://documentation.ubuntu.com/pebble/how-to/service-dependencies/) has this text:
```
You can use the [Changes and tasks] commands to get more details about the failed run.
```
This PR replaces "[Changes and tasks]" by links to the specific commands in the CLI reference.
At the bottom of the page, there's also a "see more" link to [Changes and tasks](https://documentation.ubuntu.com/pebble/reference/changes-and-tasks/), which essentially refers people to the CLI reference. With my change above, I don't think this "see more" link is needed any more, so I've removed it.
**[Preview doc build](https://canonical-ubuntu-documentation-library--641.com.readthedocs.build/pebble/how-to/service-dependencies/)**
---
Side …
=> docs: update links to changes and tasks in service dependencies guide

docs/explanation/service-start-order.md
The network team asks how to have a service B that starts only after the process of service A has exited, regardless of how long that takes. It would be helpful if we could document a workaround for this.
Closes https://github.com/canonical/pebble/issues/639.
=> docs: update service start order

internals/overlord/overlord.go, internals/overlord/servstate/export_test.go, internals/overlord/servstate/manager.go, internals/overlord/servstate/manager_test.go
Prune service logs and `serviceData` in the service manager.
- If a service is inactive, and its `currentSince` is older than `pruneWait`, it will be pruned.
- If the total number of entries of serviceData is still greater than `maxServiceData`, inactive services will be pruned even if they are _not_ older than `pruneWait` to keep the total number of serviceData entries under control. In this case, it's sorted by `currentSince` to ensure pruning older inactive services first.
Also added a few unit test cases to cover this feature. Test cases for the overlord are not updated because the outer prune loop is already tested; no integration test is added because the unit tests already cover all cases.
Fixes #539.
=> feat: prune service logs and serviceData in service manager

.github/workflows/tiobe.yaml
We've been [asked](https://chat.canonical.com/canonical/pl/yku51kozbtbdmbnaodxzgitkwh) to move the TIOBE workflow to self-hosted runners.
This is meant to optimise the time and bandwidth usage of Canonical's TICS pipelines for static code analysis in GitHub. Two thirds of the GitHub TICS pipelines under Canonical org are using them, but they want it to be closer to 100%.
I've used the `tiobe` runner (medium sized) as it seems like Pebble's static analysis shouldn't need large/2xlarge.
=> ci: move TIOBE workflow to self-hosted runners

docs/how-to/forward-logs-to-loki.md
The Loki how-to instructs the user to download the sample local configuration from the repository ```main``` while pointing to the Loki releases page for downloading the binary. The issue is that the latest (matching the configuration) release is not always the top entry on the releases page, as multiple parallel versions are maintained.
The current state of using the configuration file with the top release entry is:
```
flotter@flotter-pc:~/pebble/loki$ ./loki-linux-amd64 -config.file=loki-local-config.yaml
failed parsing config: loki-local-config.yaml: yaml: unmarshal errors:
line 30: field enable_multi_variant_queries not found in type validation.plain. Use `-config.expand-env=true` flag if you want to expand environment variables in your config file
```
Update the link to only point …
=> fix(docs): offer only latest Loki link

internals/overlord/logstate/gatherer.go, internals/plan/plan.go, internals/plan/plan_test.go
This PR removes the `plan.SyslogTarget` constant, as its not supported. This has the effect of moving the validation earlier, when checking the plan, rather than later when setting up the log gatherer.
Before (with a log target of `type: syslog`):
```
$ go run ./cmd/pebble run
2025-07-28T22:18:37.200Z [pebble] Internal error: cannot create gatherer for target "tgt": cannot create log client: unknown type "syslog" for log target "tgt"
2025-07-28T22:18:37.201Z [pebble] Started daemon.
2025-07-28T22:18:37.204Z [pebble] POST /v1/services 1.534492ms 202 (http+unix)
2025-07-28T22:18:37.206Z [pebble] Service "test1" starting: /bin/sh -c "echo test; sleep 1000"
2025-07-28T22:18:38.211Z [pebble] GET /v1/changes/1/wait 1.005821051s 200 (http+unix)
2025-07-28T22:18:38.211Z [pebble] Started default …
```
=> chore: remove unsupported "syslog" type so it's validated earlier

docs/conf.py
This PR updates links to Ops docs after the docs changed location today.
=> docs: update links to Ops docs

.github/workflows/integration-tests.yml, .github/workflows/tests.yml, .github/workflows/tiobe.yaml
Our TIOBE contact let us know that we need to update the staticcheck tool that the workflow uses, to support Go 1.24.
In order to have this work in CI, also bump the version of Go used in the unit and integration tests to 1.24, by pulling the version from `go.mod`. This removes the Go version matrix testing in the tests, but we only had a single version being tested, so the matrix wasn't really used.
=> chore: update TIOBE dependencies to support Go 1.24

internals/servicelog/formatter.go, internals/servicelog/formatter_benchmark_test.go, internals/servicelog/formatter_test.go
Because the timestamp format used is not exactly RFC3339, the Go
standard library falls back to generic formatting code that analyzes the
format on every append, this causes a lot of unnecessary work. Using a
specialized formatter specifically for the format, a ~72% improvement
is achieved.
```
$ benchstat old.txt new.txt
goos: darwin
goarch: arm64
pkg: github.com/canonical/pebble/internals/servicelog
cpu: Apple M1 Max
│   old.txt    │               new.txt               │
│    sec/op    │   sec/op     vs base                │
AppendTimestamp-10   120.55n ± 0%   33.27n ± 1%  -72.41% (p=0.000 n=10)
```
After this, the only improvement that could still be made is assuming that it's always UTC, which we already know, profililing data shows that could at most improve another ~12% …
=> perf: improve performance of serializing log timestamps

docs/explanation/security.md
This PR adds a short new section to the Security explanation describing how cryptographic technology is used.
=> docs: add section on cryptographic technology

.github/workflows/snap.yml
Also arrange arch lists alphabetically.
Fixes #687.
=> ci: add support for riscv64 architecture when building snap

internals/overlord/cmdstate/handlers.go, internals/wsutil/wsutil.go
This issue is related to https://github.com/canonical/pebble/issues/586
When the websocket connection is closed from the client side, websocket close errors are sometimes incorrectly reported:
```
2025-03-12T06:27:37.428Z [pebble] DEBUG Exec 6: started mirroring websocket
2025-03-12T06:27:37.429Z [pebble] DEBUG Exec 6: control handler started for PID 260895
2025-03-12T06:27:37.431Z [pebble] DEBUG Reaper received SIGCHLD.
2025-03-12T06:27:37.431Z [pebble] DEBUG Reaped PID 260895 which exited with code 0.
2025-03-12T06:27:37.431Z [pebble] DEBUG Detected poll(POLLHUP) event: exiting.
>>>>> 2025-03-12T06:27:37.431Z [pebble] DEBUG Exec 6: cannot get next websocket reader for PID 260895: read unix /var/lib/pebble/default/.pebble.socket->@: use of closed network connection …
```
=> fix(cmdstate,wsutil): don't report websocket close errors

internals/daemon/api_exec_test.go, internals/overlord/cmdstate/handlers.go, internals/overlord/cmdstate/manager.go
Fix `CommandManager.Connect` so that if the Pebble side has already timed out (an exec change fails before the execution object is created in the `CommandManager`), the server returns an error, causing the connection to the websocket URL to be timed out immediately.
Also, add a unit test to cover this scenario.
Closes https://github.com/canonical/pebble/issues/422.
=> fix: websocket connection timeout

.github/.golangci.yml, .github/workflows/lint.yml
The current golangci/golangci-lint-action@v3 version used on CI selects an old version of golangci-lint. The problem is that the configuration file in the project is not compatible with the current v2 releases of golangci-lint, which means I cannot run the proposed fix line locally (without downgrading).
Update CI and the configuration to v2 golangci-lint.
=> chore(golangci-lint): update to latest

internals/overlord/checkstate/manager_test.go
TestFailuresBelowThreshold was failing with this error:
```
FAIL: manager_test.go:305: ManagerSuite.TestFailuresBelowThreshold
manager_test.go:338:
c.Assert(lastTaskLog(s.overlord.State(), check.ChangeID), Matches, ".* INFO succeeded after 1 failure")
... value string = "2025-09-18T18:51:49Z INFO succeeded after 2 failures" ... regex string = ".* INFO succeeded after 1 failure"
2025-09-18T18:51:49.111Z [test] Check "chk1" failure 1/3: exit status 1 2025-09-18T18:51:49.131Z [test] Check "chk1" failure 2/3: exit status 1 2025-09-18T18:51:49.150Z [test] Check "chk1" failure 1/3: exit status 1 2025-09-18T18:51:49.243Z [test] Check "chk1" failure 1/1: check timed out after 25ms 2025-09-18T18:51:49.243Z [test] Check "chk1" threshold 1 hit, triggering action and recovering …
```
=> fix: make checkstate TestFailures tests more reliable

.github/workflows/lint.yml
Security policy guidelines will recommend that github workflows pin to known SHA instead of tags to reduce attack surface area for Github marketplace workflows. As tags have been overwritten in some exploits.
=> chore(glangci-lint): pin github workflow for v8 to specific SHA

internals/overlord/checkstate/manager_test.go
```sh
FAIL: manager_test.go:297: ManagerSuite.TestFailuresBelowThreshold
manager_test.go:332:
c.Assert(lastTaskLog(s.overlord.State(), check.ChangeID), Matches, `.* INFO succeeded after \d+ failure`)
... value string = "2025-09-30T12:25:21Z INFO succeeded after 5 failures"
... regex string = ".* INFO succeeded after \\d+ failure"
```
Tweak the test to handle the plural version of the error string.
=> test(checkstate): fix pluralise incompatible check
