README.md
This merge goes along with my comments in this discourse thread:
https://discourse.charmhub.io/t/interacting-with-pebble/4554/6
=> Refine override documentation in README

cmd/pebble/cmd_autostart.go, cmd/pebble/cmd_replan.go, cmd/pebble/cmd_restart.go, cmd/pebble/cmd_run.go, cmd/pebble/cmd_start.go, cmd/pebble/cmd_stop.go, internal/daemon/api_files.go, internal/overlord/servstate/manager_test.go, internal/plan/plan_test.go
Used staticcheck to detect a few missing error checks and unused code of concern.
=> Fix various missing error checks and missing wait mixin descriptions.

internal/plan/plan.go
* Add missing Requires field
* Copy values (not just pointers) for UserID and GroupID
These issues were found by #97.
=> Fix subtle plan.Service merging issues

.github/workflows/tests.yml, internal/daemon/api_exec_test.go, internal/daemon/api_files_test.go
These tests were somewhat tricky to run locally, and we forget, so let's at least run them automatically in GitHub actions. I'll be using this same GitHub Actions check to test https://github.com/canonical/pebble/issues/126 as well.
=> Actually run the user/group tests (as root) so we're testing that code

internal/plan/plan.go, internal/plan/plan_test.go
Also add/adjust the tests to catch these issues (in all four cases).
Fixes #132
=> Fix panic in CombineLayers for map fields

cmd/pebble/cmd_changes_test.go
This small patch revamps the tests for the actual `pebble changes` command (and not only the `pebble tasks` command, which is mostly targeted by the previous test suite).
=> Rework tests for the changes command

client/export_test.go, client/files.go, client/files_test.go, cmd/pebble/cmd_help.go, cmd/pebble/cmd_ls.go, cmd/pebble/cmd_ls_test.go
I went ahead and started implementing #107, starting with the `pebble ls` command for listing files.
I'm a bit uncomfortable about parts of my solution and would really appreciate feedback about those (in particular about the `fileInfo` struct and that struct implementing `fs.FileInfo`)
=> Implement file listing functionality

README.md
Add a section to the README about "replan" and "restart".
=> Add README docs for "replan" and "restart"

internals/cli/cmd_logs.go
=> Fix comment about channel buffer size in cmd_logs.go

internals/overlord/servstate/manager_test.go
This was causing intermittent failures in TestServiceLogs (on the order of 50% of the time), see test failure output below.
We really should refactor the tests in this package to not rely on suite-global setup and teardown, or use different suites, or something. But leaving that for a rainy day.
```
START: manager_test.go:456: S.TestServiceLogs
START: manager_test.go:147: S.SetUpTest
PASS: manager_test.go:147: S.SetUpTest	0.000s
2023-06-19T11:13:02.294Z [test] Service "test1" starting: /bin/sh -c "echo test1 | tee -a /tmp/check-270658404/27/log.txt; sleep 10" 2023-06-19T11:13:02.346Z [test] Service "test2" starting: /bin/sh -c "echo test2 | tee -a /tmp/check-270658404/27/log.txt; sleep 10" 2023-06-19T11:13:02.368Z [test] Service "usrtest" starting: /bin/sh -c "id -n -u | tee -a …
```
=> Fix flaky TestServiceLogs due to TestCurrentUserGroup reusing manager

README.md
These features have been implemented now:
* rm (#146)
* push (#147)
* pull (#148)
=> docs(README.md): rm, push and pull are now implemented

README.md
Add some CI badges for easier tracking on releases.juju.is
=> docs: add CI badges to README

internals/cli/wait.go
This commit exports a function to display a progress bar tracking the progress of a change ID.
Unlike the wait function which remains unexported, this new function does not require a waitMixin.
Motivation: allow projects that import Pebble and add commands to its CLI to use the same waiting logic and UI.
The unused skipAbort field of the waitMixin has been removed.
=> feat(wait): export cli.Wait function

HACKING.md, cmd/version.go
Updating the README with the actual current process.
=> Update version to v1.9.0 for release; flesh out release instructions

docs/how-to/service-dependencies.md, docs/reference/health-checks.md, docs/reference/layer-specification.md
[Recent changes made to the README](https://github.com/canonical/pebble/commit/c330d5f0f37cd7c47b4ec3ce094b39e43fb3f6b4) should be made to the doc site as well.
Closes #468.
=> docs: tweaks according to latest readme changes

docs/how-to/manage-identities.md
Clarify what "this" refers to now that *this* is in a different section.
=> docs: tweak per Anne's feedback

docs/reference/api.md, docs/specs/openapi.yaml
Pebble HTTP API spec refactor.
Closes #554.
Preview: https://canonical-pebble--555.com.readthedocs.build/en/555/reference/api/
=> docs: update api spec according to suggestions from ben

internals/overlord/backend.go
This was completely unused -- removing.
=> chore: remove unused requestRestart field

docs/reference/health-checks.md
Add docs for how to test health checks with `pebble check --refresh`.
=> docs: add a section on pebble check refresh

client/client.go, client/exec.go, internals/daemon/api_tasks.go, internals/overlord/cmdstate/handlers.go
Minor refactor for logging and error-handling related to the websocket connection.
=> chore: logging and error handling improvement related to websocket connection
